apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-groups-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affiliate-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-groups: "group-*"

target:
  kind: Deployment
  name: affiliate-marketing
