apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: real-estate-marketing-dev

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: real-estate-marketing
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: real-estate-marketing

configMapGenerator:
  - name: real-estate-marketing-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DEBUG=true

commonLabels:
  environment: development

images:
  - name: grcclaw/real-estate-marketing
    newTag: dev
