apiVersion: v1
kind: Service
metadata:
  name: real-estate-marketing
  labels:
    app: real-estate-marketing
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: real-estate-marketing
