apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-pvs-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agency-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-pvs: "agency-marketing-*"

target:
  kind: Deployment
  name: agency-marketing
