apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-nodes-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agency-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-nodes: "node-*"

target:
  kind: Deployment
  name: agency-marketing
