apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sealed-secrets-patch
patch: |-
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agency-marketing-sealed-secrets
spec:
  encryptedData:
    DATABASE_URL: AgByA...
    API_KEY: AgByB...
    JWT_SECRET: AgByC...

target:
  kind: Deployment
  name: agency-marketing
