apiVersion: builtin
kind: PatchTransformer
metadata:
  name: tailscale-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agency-marketing
spec:
  template:
    metadata:
      annotations:
        tailscale.com/enable: "true"

target:
  kind: Deployment
  name: agency-marketing
