apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: grc-claw-observability
data:
  config.yaml: "auth_enabled: false\nserver:\n  http_listen_port: 3100\ncommon:\n\
    \  instance_addr: 127.0.0.1\n  path_prefix: /loki\n  storage:\n    filesystem:\n\
    \      chunks_directory: /loki/chunks\n      rules_directory: /loki/rules\n  replication_factor:\
    \ 1\n  ring:\n    kvstore:\n      store: inmemory\nschema_config:\n  configs:\n\
    \    - from: 2024-01-01\n      store: tsdb\n      object_store: filesystem\n \
    \     schema: v13\n      index:\n        prefix: index_\n        period: 24h\n"
