apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: product-recommendations-restore
spec:
  backupName: product-recommendations-backup
  includedNamespaces:
    - product-recommendations-prod
  restorePVs: true

target:
  kind: Deployment
  name: product-recommendations
