apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-clusters-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-recommendations
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-clusters: "cluster1"

target:
  kind: Deployment
  name: product-recommendations
