apiVersion: builtin
kind: PatchTransformer
metadata:
  name: serviceaccount-patch
patch: |-
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-recommendations-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/product-recommendations-role

target:
  kind: Deployment
  name: product-recommendations
