apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-mig-fan-tachometer-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppc-manager
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-mig-fan-tachometer: "1200"

target:
  kind: Deployment
  name: ppc-manager
