apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-mig-fan-mode-hot-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppc-manager
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-mig-fan-mode-hot: "false"

target:
  kind: Deployment
  name: ppc-manager
