apiVersion: builtin
kind: PatchTransformer
metadata:
  name: pdb-patch
patch: |-
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ppc-manager-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ppc-manager

target:
  kind: Deployment
  name: ppc-manager
