apiVersion: builtin
kind: VarTransformer
metadata:
  name: var-config
vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: ppc-manager
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: NAMESPACE
    objref:
      kind: Namespace
      name: ppc-manager-prod
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
