apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: customer-service-restore
spec:
  backupName: customer-service-backup
  includedNamespaces:
    - customer-service-prod
  restorePVs: true

target:
  kind: Deployment
  name: customer-service
