apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-mig-fan-period-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-mig-fan-period: "0.04"

target:
  kind: Deployment
  name: customer-service
