apiVersion: builtin
kind: PatchTransformer
metadata:
  name: priorityclass-patch
patch: |-
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: customer-service-priority
value: 1000
globalDefault: false
description: "Priority class for customer-service service"

target:
  kind: Deployment
  name: customer-service
