apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: saas-marketing-restore
spec:
  backupName: saas-marketing-backup
  includedNamespaces:
    - saas-marketing-prod
  restorePVs: true

target:
  kind: Deployment
  name: saas-marketing
