apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-pvcs-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-pvcs: "saas-marketing-*"

target:
  kind: Deployment
  name: saas-marketing
