apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: resume-parser

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: resume-parser
    newTag: latest

commonLabels:
  app: resume-parser
  managed-by: kustomize
