apiVersion: v1
kind: Service
metadata:
  name: content-generator
  labels:
    app.kubernetes.io/name: content-generator
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: content-generator
