apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketing-compliance-staging

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: marketing-compliance
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: marketing-compliance

configMapGenerator:
  - name: marketing-compliance-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - DEBUG=false

commonLabels:
  environment: staging

images:
  - name: grcclaw/marketing-compliance
    newTag: staging
