apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-recommendations-prod

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: product-recommendations
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: product-recommendations
  - path: ../../patches/security-patch.yaml
    target:
      kind: Deployment
      name: product-recommendations

configMapGenerator:
  - name: product-recommendations-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
      - DEBUG=false

commonLabels:
  environment: production

images:
  - name: grcclaw/product-recommendations
    newTag: stable

replicas:
  - name: product-recommendations
    count: 3
