apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-training
spec:
  template:
    spec:
      containers:
        - name: onboarding-training
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
