apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppc-manager
spec:
  template:
    spec:
      containers:
        - name: ppc-manager
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
