apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-mig-fan-mode-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-attribution
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-mig-fan-mode: "auto"

target:
  kind: Deployment
  name: marketing-attribution
