apiVersion: builtin
kind: PatchTransformer
metadata:
  name: pdb-patch
patch: |-
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: marketing-attribution-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: marketing-attribution

target:
  kind: Deployment
  name: marketing-attribution
