import type { CrossMapping } from '../types.js';

export const FEDRAMP_NIST80053_MAPPINGS: CrossMapping[] = [
  { sourceFramework: 'fedramp', sourceControl: 'AC-1', targetFramework: 'nist_800_53', targetControl: 'AC-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AC-2', targetFramework: 'nist_800_53', targetControl: 'AC-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AC-3', targetFramework: 'nist_800_53', targetControl: 'AC-3', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AC-6', targetFramework: 'nist_800_53', targetControl: 'AC-6', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AC-7', targetFramework: 'nist_800_53', targetControl: 'AC-7', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AC-8', targetFramework: 'nist_800_53', targetControl: 'AC-8', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AU-1', targetFramework: 'nist_800_53', targetControl: 'AU-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AU-2', targetFramework: 'nist_800_53', targetControl: 'AU-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AU-3', targetFramework: 'nist_800_53', targetControl: 'AU-3', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AU-6', targetFramework: 'nist_800_53', targetControl: 'AU-6', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'AU-12', targetFramework: 'nist_800_53', targetControl: 'AU-12', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'CA-1', targetFramework: 'nist_800_53', targetControl: 'CA-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'CA-2', targetFramework: 'nist_800_53', targetControl: 'CA-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'CM-1', targetFramework: 'nist_800_53', targetControl: 'CM-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'CM-2', targetFramework: 'nist_800_53', targetControl: 'CM-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'CM-6', targetFramework: 'nist_800_53', targetControl: 'CM-6', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'CM-8', targetFramework: 'nist_800_53', targetControl: 'CM-8', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'IA-1', targetFramework: 'nist_800_53', targetControl: 'IA-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'IA-2', targetFramework: 'nist_800_53', targetControl: 'IA-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'IA-5', targetFramework: 'nist_800_53', targetControl: 'IA-5', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'IA-8', targetFramework: 'nist_800_53', targetControl: 'IA-8', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'IR-1', targetFramework: 'nist_800_53', targetControl: 'IR-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'IR-4', targetFramework: 'nist_800_53', targetControl: 'IR-4', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'IR-6', targetFramework: 'nist_800_53', targetControl: 'IR-6', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'MA-1', targetFramework: 'nist_800_53', targetControl: 'MA-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'MA-2', targetFramework: 'nist_800_53', targetControl: 'MA-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'MP-1', targetFramework: 'nist_800_53', targetControl: 'MP-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'MP-2', targetFramework: 'nist_800_53', targetControl: 'MP-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'PE-1', targetFramework: 'nist_800_53', targetControl: 'PE-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'PE-2', targetFramework: 'nist_800_53', targetControl: 'PE-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'PL-1', targetFramework: 'nist_800_53', targetControl: 'PL-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'PM-1', targetFramework: 'nist_800_53', targetControl: 'PM-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'PS-1', targetFramework: 'nist_800_53', targetControl: 'PS-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'RA-1', targetFramework: 'nist_800_53', targetControl: 'RA-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'RA-3', targetFramework: 'nist_800_53', targetControl: 'RA-3', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'RA-5', targetFramework: 'nist_800_53', targetControl: 'RA-5', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SA-1', targetFramework: 'nist_800_53', targetControl: 'SA-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SA-3', targetFramework: 'nist_800_53', targetControl: 'SA-3', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SA-4', targetFramework: 'nist_800_53', targetControl: 'SA-4', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SA-5', targetFramework: 'nist_800_53', targetControl: 'SA-5', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SC-1', targetFramework: 'nist_800_53', targetControl: 'SC-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SC-7', targetFramework: 'nist_800_53', targetControl: 'SC-7', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SC-8', targetFramework: 'nist_800_53', targetControl: 'SC-8', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SC-12', targetFramework: 'nist_800_53', targetControl: 'SC-12', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SC-13', targetFramework: 'nist_800_53', targetControl: 'SC-13', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SC-28', targetFramework: 'nist_800_53', targetControl: 'SC-28', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SI-1', targetFramework: 'nist_800_53', targetControl: 'SI-1', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SI-2', targetFramework: 'nist_800_53', targetControl: 'SI-2', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SI-3', targetFramework: 'nist_800_53', targetControl: 'SI-3', confidence: 1.0, relationship: 'equivalent' },
  { sourceFramework: 'fedramp', sourceControl: 'SI-4', targetFramework: 'nist_800_53', targetControl: 'SI-4', confidence: 1.0, relationship: 'equivalent' },
];

export const FEDRAMP_NIST80053_PAIR = { source: 'fedramp', target: 'nist_800_53' };
