apiVersion: builtin
kind: PatchTransformer
metadata:
  name: kube-router-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-enablement
spec:
  template:
    metadata:
      annotations:
        kube-router.io/enable: "true"

target:
  kind: Deployment
  name: broker-enablement
