apiVersion: builtin
kind: PatchTransformer
metadata:
  name: pdb-patch
patch: |-
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: broker-enablement-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: broker-enablement

target:
  kind: Deployment
  name: broker-enablement
