apiVersion: builtin
kind: PatchTransformer
metadata:
  name: serviceaccount-patch
patch: |-
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influencer-marketing-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/influencer-marketing-role

target:
  kind: Deployment
  name: influencer-marketing
