apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-service-dev

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: customer-service
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: customer-service

configMapGenerator:
  - name: customer-service-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DEBUG=true

commonLabels:
  environment: development

images:
  - name: grcclaw/customer-service
    newTag: dev
