apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: healthcare-marketing-restore
spec:
  backupName: healthcare-marketing-backup
  includedNamespaces:
    - healthcare-marketing-prod
  restorePVs: true

target:
  kind: Deployment
  name: healthcare-marketing
