apiVersion: builtin
kind: PatchTransformer
metadata:
  name: kyverno-patch
patch: |-
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: healthcare-marketing-policy
spec:
  validationFailureAction: Enforce
  rules:
    - name: validate-resources
      match:
        resources:
          kinds:
            - Deployment
          selector:
            matchLabels:
              app.kubernetes.io/name: healthcare-marketing
      validate:
        message: "Resource requests and limits are required"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - resources:
                      requests:
                        memory: "?*"
                        cpu: "?*"
                      limits:
                        memory: "?*"
                        cpu: "?*"

target:
  kind: Deployment
  name: healthcare-marketing
