apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sonarqube-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-marketing
spec:
  template:
    metadata:
      annotations:
        sonarqube.org/project-key: healthcare-marketing

target:
  kind: Deployment
  name: healthcare-marketing
