"""Core utilities and shared components."""

from sales_forecaster.core.cache import SimpleCache, cached, get_redis_client
from sales_forecaster.core.settings import Settings, get_settings, setup_logging
from sales_forecaster.core.exceptions import (
    AnalysisError,
    AuthenticationError,
    ConfigurationError,
    DataCollectionError,
    IntegrationError,
    PipelineError,
    PredictionError,
    RateLimitError,
    SalesForecasterError,
    ValidationError,
)
from sales_forecaster.core.metrics import (
    record_agent_error,
    record_data_collected,
    record_forecast_accuracy,
    record_pipeline_complete,
    record_pipeline_start,
    track_forecast_request,
    track_pipeline_stage,
)
from sales_forecaster.core.models import (
    ActionRecommendation,
    AnalysisResult,
    ApiResponse,
    DataSource,
    ForecastPeriod,
    ForecastPoint,
    ForecastResult,
    HealthCheck,
    HealthStatus,
    PerformanceMetrics,
    PipelineRun,
    PipelineStage,
    PipelineStatus,
    SalesRecord,
)
from sales_forecaster.core.retry import async_retry, calculate_backoff, is_retryable_error

__all__ = [
    "ActionRecommendation",
    "AnalysisError",
    "AnalysisResult",
    "ApiResponse",
    "AuthenticationError",
    "ConfigurationError",
    "DataCollectionError",
    "DataSource",
    "ForecastPeriod",
    "ForecastPoint",
    "ForecastResult",
    "HealthCheck",
    "HealthStatus",
    "IntegrationError",
    "PerformanceMetrics",
    "PipelineError",
    "PipelineRun",
    "PredictionError",
    "PipelineStage",
    "PipelineStatus",
    "RateLimitError",
    "SalesForecasterError",
    "SalesRecord",
    "SimpleCache",
    "ValidationError",
    "async_retry",
    "cached",
    "calculate_backoff",
    "get_redis_client",
    "is_retryable_error",
    "record_agent_error",
    "record_data_collected",
    "record_forecast_accuracy",
    "record_pipeline_complete",
    "record_pipeline_start",
    "track_forecast_request",
    "track_pipeline_stage",
    "Settings",
    "get_settings",
    "setup_logging",
]
