apiVersion: builtin
kind: PatchTransformer
metadata:
  name: datree-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-marketing
spec:
  template:
    metadata:
      annotations:
        datree.skip/DEPLOYMENT: "false"

target:
  kind: Deployment
  name: real-estate-marketing
