apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replacement-config
replacements:
  - source:
      kind: ConfigMap
      name: real-estate-marketing-config
      fieldPath: data.LOG_LEVEL
    targets:
      - select:
          kind: Deployment
          name: real-estate-marketing
        fieldPaths:
          - spec.template.spec.containers.[name=real-estate-marketing].env.[name=LOG_LEVEL].value
        options:
          create: true
