apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-optimizer
spec:
  template:
    spec:
      containers:
        - name: campaign-optimizer
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
