apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: finance-marketing-restore
spec:
  backupName: finance-marketing-backup
  includedNamespaces:
    - finance-marketing-prod
  restorePVs: true

target:
  kind: Deployment
  name: finance-marketing
