apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onboarding-training-dev

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: onboarding-training
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: onboarding-training

configMapGenerator:
  - name: onboarding-training-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DEBUG=true

commonLabels:
  environment: development

images:
  - name: grcclaw/onboarding-training
    newTag: dev
