apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-services-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-intelligence
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-services: "business-intelligence-*"

target:
  kind: Deployment
  name: business-intelligence
