apiVersion: builtin
kind: PatchTransformer
metadata:
  name: weave-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-intelligence
spec:
  template:
    metadata:
      annotations:
        weave.works/enable: "true"

target:
  kind: Deployment
  name: business-intelligence
