apiVersion: v1
kind: Secret
metadata:
  name: employer-branding-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  LANGCHAIN_API_KEY: ""
  GLASSDOOR_API_KEY: ""
  LINKEDIN_API_KEY: ""
  INDEED_API_KEY: ""
