"""
Metrics Registry — all 40+ metrics from the GRC_Claw Unified Metrics Layer.

Pre-seeded metric definitions for 8 categories (UC1-UC8) and 12 agentic AI
metrics (AG-001 through AG-012), with thresholds, escalation tiers, and
dashboard layer assignments per the metrics specification.
"""

from __future__ import annotations

from .models import DashboardLayer, MetricCategory, MetricDefinition

# ─── UC-1: Asset Inventory & Coverage ────────────────────────────────────────


UC1_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC1-001",
        name="AI System Inventory Coverage",
        category=MetricCategory.ASSET_INVENTORY,
        description="Percentage of production AI systems registered with named owner and risk classification",
        formula="(Registered systems with owner AND risk classification / Total discovered systems) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=85.0,
        tier3_threshold=80.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.EXECUTIVE, DashboardLayer.PROGRAM, DashboardLayer.OPERATING],
        owner_role="Head of AI QE",
        data_sources=["ai_asset_registry", "ci_cd_pipeline", "cloud_api", "network_analysis"],
        tags=["inventory", "coverage", "governance"],
    ),
    MetricDefinition(
        metric_id="UC1-002",
        name="High-Risk Systems Under Governance",
        category=MetricCategory.ASSET_INVENTORY,
        description="Percentage of high-risk AI systems under active governance",
        formula="(High-risk systems with assessment AND controls AND monitoring / Total high-risk systems) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=95.0,
        tier2_threshold=90.0,
        tier3_threshold=85.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="6h",
        dashboard_layers=[DashboardLayer.PROGRAM, DashboardLayer.EXECUTIVE],
        owner_role="AI Risk Officer",
        data_sources=["grc_platform", "control_mapping_engine", "observability_stack"],
        tags=["high-risk", "governance", "assessment"],
    ),
    MetricDefinition(
        metric_id="UC1-003",
        name="Agent Identity Coverage",
        category=MetricCategory.ASSET_INVENTORY,
        description="Percentage of discovered AI agents with unique NHI, named owner, and registered",
        formula="(Agents with NHI AND owner AND registered / Total discovered agents) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="4h",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="CISO",
        data_sources=["agent_registry", "nhi_vault", "framework_telemetry", "api_gateway"],
        tags=["agent", "identity", "nhi"],
    ),
    MetricDefinition(
        metric_id="UC1-004",
        name="Business Unit Participation",
        category=MetricCategory.ASSET_INVENTORY,
        description="Percentage of business units with designated AI liaison",
        formula="(BUs with AI liaison / Total business units) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CAIO",
        data_sources=["hr_system", "grc_platform"],
        tags=["business-unit", "liaison", "participation"],
    ),
    MetricDefinition(
        metric_id="UC1-005",
        name="Vendor Coverage",
        category=MetricCategory.ASSET_INVENTORY,
        description="Percentage of third-party AI vendors with completed due diligence",
        formula="(Vendors with completed DD / Total AI vendors) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.PROGRAM, DashboardLayer.OPERATING],
        owner_role="CPO",
        data_sources=["vendor_management", "ai_asset_registry", "procurement", "api_gateway"],
        tags=["vendor", "due-diligence", "coverage"],
    ),
]


# ─── UC-2: Risk & Compliance Posture ─────────────────────────────────────────


UC2_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC2-001",
        name="Risk Assessments Complete",
        category=MetricCategory.RISK_COMPLIANCE,
        description="Percentage of in-scope AI systems with completed risk assessments",
        formula="(Systems with completed risk assessment / Total in-scope systems) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="6h",
        dashboard_layers=[DashboardLayer.PROGRAM, DashboardLayer.EXECUTIVE],
        owner_role="AI Risk Officer",
        data_sources=["grc_platform"],
        tags=["risk", "assessment", "compliance"],
    ),
    MetricDefinition(
        metric_id="UC2-002",
        name="Open High-Risk Findings",
        category=MetricCategory.RISK_COMPLIANCE,
        description="Count of open critical and high-severity findings",
        formula="COUNT(findings WHERE severity IN (critical, high) AND status = open)",
        unit="count",
        target=0.0,
        tier1_threshold=5.0,
        tier2_threshold=10.0,
        tier3_threshold=20.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.PROGRAM, DashboardLayer.EXECUTIVE],
        owner_role="AI Risk Officer",
        data_sources=["grc_platform", "audit_management", "incident_management", "red_team"],
        tags=["findings", "high-risk", "open"],
    ),
    MetricDefinition(
        metric_id="UC2-003",
        name="Regulatory Alignment Score",
        category=MetricCategory.RISK_COMPLIANCE,
        description="Percentage of applicable regulatory requirements with current verifiable evidence",
        formula="(Requirements with current verifiable evidence / Total applicable requirements) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=85.0,
        tier2_threshold=80.0,
        tier3_threshold=75.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="weekly",
        dashboard_layers=[DashboardLayer.EXECUTIVE, DashboardLayer.PROGRAM, DashboardLayer.OPERATING],
        owner_role="CCO",
        data_sources=["evidence_store", "framework_mapping_engine"],
        tags=["regulatory", "compliance", "evidence"],
    ),
    MetricDefinition(
        metric_id="UC2-004",
        name="Policy Adherence Rate",
        category=MetricCategory.RISK_COMPLIANCE,
        description="Percentage of AI projects passing mandatory pre-deployment governance review",
        formula="(Projects passing pre-deployment review / Total projects entering review) × 100",
        unit="percent",
        target=95.0,
        tier1_threshold=90.0,
        tier2_threshold=85.0,
        tier3_threshold=80.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="per-review",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="AI Governance Lead",
        data_sources=["grc_platform", "ci_cd_gates"],
        tags=["policy", "adherence", "pre-deployment"],
    ),
    MetricDefinition(
        metric_id="UC2-005",
        name="Policy-to-Enforcement Gap",
        category=MetricCategory.RISK_COMPLIANCE,
        description="Percentage of AI policy statements with corresponding technical controls",
        formula="(Policy statements with verified technical control / Total policy statements) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CISO",
        data_sources=["policy_management", "control_mapping_engine"],
        tags=["policy", "enforcement", "controls"],
    ),
    MetricDefinition(
        metric_id="UC2-006",
        name="Audit Findings",
        category=MetricCategory.RISK_COMPLIANCE,
        description="Count of findings from internal and external audits per year",
        formula="COUNT(audit_findings WHERE audit_date IN current_year)",
        unit="count",
        target=2.0,
        tier1_threshold=2.0,
        tier2_threshold=5.0,
        tier3_threshold=10.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="per-audit",
        dashboard_layers=[DashboardLayer.PROGRAM, DashboardLayer.EXECUTIVE],
        owner_role="Internal Audit",
        data_sources=["audit_management"],
        tags=["audit", "findings", "annual"],
    ),
]


# ─── UC-3: Operational Performance & Reliability ─────────────────────────────


UC3_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC3-001",
        name="Model Accuracy / F1 Score",
        category=MetricCategory.OPERATIONAL_PERFORMANCE,
        description="ML performance metrics against approved baselines",
        formula="Accuracy = (TP+TN)/(TP+TN+FP+FN); F1 = 2×(P×R)/(P+R)",
        unit="score",
        target=0.95,
        tier1_threshold=0.93,
        tier2_threshold=0.90,
        tier3_threshold=0.85,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="per-deployment",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["mlflow", "wandb", "evaluation_pipeline"],
        tags=["model", "accuracy", "f1", "performance"],
    ),
    MetricDefinition(
        metric_id="UC3-002",
        name="Model Drift Detection",
        category=MetricCategory.OPERATIONAL_PERFORMANCE,
        description="Statistical drift in model inputs, outputs, or performance",
        formula="PSI = Σ(Actual% - Expected%) × ln(Actual%/Expected%)",
        unit="psi",
        target=0.1,
        tier1_threshold=0.1,
        tier2_threshold=0.2,
        tier3_threshold=0.3,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["arize", "fiddler", "datadog"],
        tags=["drift", "psi", "monitoring"],
    ),
    MetricDefinition(
        metric_id="UC3-003",
        name="System Availability / Uptime",
        category=MetricCategory.OPERATIONAL_PERFORMANCE,
        description="Percentage of time AI systems are available within SLO",
        formula="(Total time - Downtime) / Total time × 100",
        unit="percent",
        target=99.5,
        tier1_threshold=99.5,
        tier2_threshold=99.0,
        tier3_threshold=98.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="SRE",
        data_sources=["datadog", "prometheus", "api_health_checks"],
        tags=["availability", "uptime", "slo"],
    ),
    MetricDefinition(
        metric_id="UC3-004",
        name="Response Time (P95/P99)",
        category=MetricCategory.OPERATIONAL_PERFORMANCE,
        description="Latency percentiles for AI system responses",
        formula="P95/P99 from response time distribution",
        unit="milliseconds",
        target=500.0,
        tier1_threshold=500.0,
        tier2_threshold=750.0,
        tier3_threshold=1000.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="SRE",
        data_sources=["datadog_apm", "api_gateway", "model_serving"],
        tags=["latency", "p95", "p99", "performance"],
    ),
    MetricDefinition(
        metric_id="UC3-005",
        name="Human Override Rate",
        category=MetricCategory.OPERATIONAL_PERFORMANCE,
        description="Percentage of AI-influenced decisions overridden by human reviewers",
        formula="(Decisions overridden / Total AI-influenced decisions) × 100",
        unit="percent",
        target=10.0,
        tier1_threshold=15.0,
        tier2_threshold=20.0,
        tier3_threshold=30.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="weekly",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="Business Owner",
        data_sources=["decision_logs", "review_workflow"],
        tags=["override", "human-in-the-loop", "decisions"],
    ),
]


# ─── UC-4: Incident & Exception Management ───────────────────────────────────


UC4_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC4-001",
        name="AI Incidents (by severity)",
        category=MetricCategory.INCIDENT_MANAGEMENT,
        description="Count of AI-related incidents categorized by severity",
        formula="COUNT(incidents WHERE incident_type = AI-related) GROUP BY severity",
        unit="count",
        target=0.0,
        tier1_threshold=1.0,
        tier2_threshold=5.0,
        tier3_threshold=10.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.EXECUTIVE, DashboardLayer.PROGRAM, DashboardLayer.OPERATING],
        owner_role="AI Risk Officer",
        data_sources=["servicenow", "siem", "soar"],
        tags=["incident", "severity", "ai-related"],
    ),
    MetricDefinition(
        metric_id="UC4-002",
        name="Mean Time to Detect (MTTD)",
        category=MetricCategory.INCIDENT_MANAGEMENT,
        description="Average time from AI incident occurrence to detection",
        formula="AVG(detection_timestamp - occurrence_timestamp)",
        unit="hours",
        target=1.0,
        tier1_threshold=1.0,
        tier2_threshold=4.0,
        tier3_threshold=24.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="SRE",
        data_sources=["incident_management", "monitoring"],
        tags=["mttd", "detection", "incident"],
    ),
    MetricDefinition(
        metric_id="UC4-003",
        name="Mean Time to Resolve (MTTR)",
        category=MetricCategory.INCIDENT_MANAGEMENT,
        description="Average time from AI incident detection to resolution",
        formula="AVG(resolution_timestamp - detection_timestamp)",
        unit="hours",
        target=4.0,
        tier1_threshold=4.0,
        tier2_threshold=8.0,
        tier3_threshold=24.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="AI Risk Officer",
        data_sources=["incident_management"],
        tags=["mttr", "resolution", "incident"],
    ),
    MetricDefinition(
        metric_id="UC4-004",
        name="Incidents Resolved Within SLA",
        category=MetricCategory.INCIDENT_MANAGEMENT,
        description="Percentage of AI incidents resolved within defined SLA",
        formula="(Incidents resolved within SLA / Total resolved incidents) × 100",
        unit="percent",
        target=95.0,
        tier1_threshold=95.0,
        tier2_threshold=90.0,
        tier3_threshold=85.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="AI Risk Officer",
        data_sources=["incident_management"],
        tags=["sla", "resolution", "compliance"],
    ),
    MetricDefinition(
        metric_id="UC4-005",
        name="Recurring Incidents",
        category=MetricCategory.INCIDENT_MANAGEMENT,
        description="Percentage of incidents that are recurrences within 90 days",
        formula="(Recurring incidents / Total incidents) × 100",
        unit="percent",
        target=10.0,
        tier1_threshold=10.0,
        tier2_threshold=15.0,
        tier3_threshold=20.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="AI Risk Officer",
        data_sources=["incident_management"],
        tags=["recurrence", "incident", "root-cause"],
    ),
    MetricDefinition(
        metric_id="UC4-006",
        name="Root Cause Analysis Completion",
        category=MetricCategory.INCIDENT_MANAGEMENT,
        description="Percentage of AI incidents with completed RCA",
        formula="(Incidents with completed RCA / Total incidents requiring RCA) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=100.0,
        tier2_threshold=90.0,
        tier3_threshold=80.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="AI Risk Officer",
        data_sources=["incident_management"],
        tags=["rca", "root-cause", "incident"],
    ),
]


# ─── UC-5: Remediation & Continuous Improvement ──────────────────────────────


UC5_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC5-001",
        name="Remediation Velocity (Median Days)",
        category=MetricCategory.REMEDIATION_IMPROVEMENT,
        description="Median days from finding identification to verified closure",
        formula="MEDIAN(closure_date - identification_date) WHERE finding_status = closed",
        unit="days",
        target=30.0,
        tier1_threshold=30.0,
        tier2_threshold=45.0,
        tier3_threshold=60.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="AI Programme Office",
        data_sources=["jira", "servicenow"],
        tags=["remediation", "velocity", "median"],
    ),
    MetricDefinition(
        metric_id="UC5-002",
        name="Remediation Velocity (Critical)",
        category=MetricCategory.REMEDIATION_IMPROVEMENT,
        description="Median days for critical-severity findings from identification to closure",
        formula="MEDIAN(closure_date - identification_date) WHERE severity = critical",
        unit="days",
        target=45.0,
        tier1_threshold=45.0,
        tier2_threshold=60.0,
        tier3_threshold=90.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM, DashboardLayer.EXECUTIVE],
        owner_role="AI Programme Office",
        data_sources=["jira", "servicenow"],
        tags=["remediation", "critical", "velocity"],
    ),
    MetricDefinition(
        metric_id="UC5-003",
        name="Governance Committee Throughput",
        category=MetricCategory.REMEDIATION_IMPROVEMENT,
        description="Number of governance decisions made per quarter",
        formula="COUNT(decisions WHERE committee = AI_Governance AND quarter = measurement_quarter)",
        unit="count",
        target=50.0,
        tier1_threshold=25.0,
        tier2_threshold=12.0,
        tier3_threshold=0.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="eq",
        measurement_frequency="quarterly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CAIO",
        data_sources=["grc_platform"],
        tags=["governance", "committee", "throughput"],
    ),
    MetricDefinition(
        metric_id="UC5-004",
        name="Governance ROI",
        category=MetricCategory.REMEDIATION_IMPROVEMENT,
        description="Ratio of value delivered by AI governance to cost of governance operations",
        formula="(Value delivered - Governance cost) / Governance cost",
        unit="ratio",
        target=1.0,
        tier1_threshold=1.0,
        tier2_threshold=0.5,
        tier3_threshold=0.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="quarterly",
        dashboard_layers=[DashboardLayer.EXECUTIVE],
        owner_role="CFO",
        data_sources=["finance_system", "grc_platform"],
        tags=["roi", "governance", "value"],
    ),
    MetricDefinition(
        metric_id="UC5-005",
        name="Maturity Level (Self-Assessed)",
        category=MetricCategory.REMEDIATION_IMPROVEMENT,
        description="Self-assessed AI governance maturity on 1-5 scale",
        formula="AVG(maturity_scores across 6 dimensions)",
        unit="score",
        target=3.0,
        tier1_threshold=3.0,
        tier2_threshold=2.5,
        tier3_threshold=2.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="annually",
        dashboard_layers=[DashboardLayer.EXECUTIVE],
        owner_role="CAIO",
        data_sources=["maturity_assessment"],
        tags=["maturity", "self-assessed", "annual"],
    ),
]


# ─── UC-6: Third-Party & Supply Chain Risk ───────────────────────────────────


UC6_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC6-001",
        name="Third-Party AI Risk Exposure",
        category=MetricCategory.THIRD_PARTY_RISK,
        description="Count of unassured high-risk third-party AI vendors in production",
        formula="COUNT(vendors WHERE risk_tier = high AND DD != complete AND status = active)",
        unit="count",
        target=0.0,
        tier1_threshold=0.0,
        tier2_threshold=1.0,
        tier3_threshold=3.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CPO",
        data_sources=["vendor_management", "grc_platform", "ai_asset_registry"],
        tags=["third-party", "vendor", "risk"],
    ),
    MetricDefinition(
        metric_id="UC6-002",
        name="Vendor Assessment Turnaround",
        category=MetricCategory.THIRD_PARTY_RISK,
        description="Average days from vendor onboarding request to completed assessment",
        formula="AVG(completion_date - request_date) WHERE assessment_type = vendor_due_diligence",
        unit="days",
        target=30.0,
        tier1_threshold=30.0,
        tier2_threshold=45.0,
        tier3_threshold=60.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CPO",
        data_sources=["vendor_management"],
        tags=["vendor", "assessment", "turnaround"],
    ),
    MetricDefinition(
        metric_id="UC6-003",
        name="Fourth-Party Risk Exposure",
        category=MetricCategory.THIRD_PARTY_RISK,
        description="Count of unassured fourth-party dependencies",
        formula="COUNT(fourth_party WHERE assurance_status != complete AND risk_tier IN (high, critical))",
        unit="count",
        target=0.0,
        tier1_threshold=0.0,
        tier2_threshold=5.0,
        tier3_threshold=10.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CPO",
        data_sources=["vendor_management"],
        tags=["fourth-party", "supply-chain", "risk"],
    ),
    MetricDefinition(
        metric_id="UC6-004",
        name="Vendor Due Diligence Coverage",
        category=MetricCategory.THIRD_PARTY_RISK,
        description="Percentage of third-party AI vendors with completed due diligence",
        formula="(Vendors with completed DD / Total AI vendors) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CPO",
        data_sources=["vendor_management", "ai_asset_registry"],
        tags=["vendor", "due-diligence", "coverage"],
    ),
]


# ─── UC-7: Economic Value & Accountability ───────────────────────────────────


UC7_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC7-001",
        name="AI Value Delivered",
        category=MetricCategory.ECONOMIC_VALUE,
        description="Dollar value generated by AI initiatives",
        formula="Σ(revenue_attributable) + Σ(cost_reduction) + Σ(efficiency_gains)",
        unit="usd",
        target=0.0,
        tier1_threshold=0.0,
        tier2_threshold=0.0,
        tier3_threshold=0.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="quarterly",
        dashboard_layers=[DashboardLayer.EXECUTIVE, DashboardLayer.PROGRAM],
        owner_role="CFO",
        data_sources=["finance_system", "pmo", "business_metrics"],
        tags=["value", "revenue", "economic"],
    ),
    MetricDefinition(
        metric_id="UC7-002",
        name="Cost Avoidance from Risk Prevention",
        category=MetricCategory.ECONOMIC_VALUE,
        description="Dollar value of costs avoided through AI risk prevention",
        formula="Σ(probability × impact × mitigation_effectiveness)",
        unit="usd",
        target=0.0,
        tier1_threshold=0.0,
        tier2_threshold=0.0,
        tier3_threshold=0.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="quarterly",
        dashboard_layers=[DashboardLayer.EXECUTIVE, DashboardLayer.PROGRAM],
        owner_role="CFO",
        data_sources=["risk_register", "control_testing"],
        tags=["cost-avoidance", "risk", "prevention"],
    ),
    MetricDefinition(
        metric_id="UC7-003",
        name="AI Spend Allocation Rate",
        category=MetricCategory.ECONOMIC_VALUE,
        description="Percentage of total AI spend attributed to specific owner and cost center",
        formula="(Attributed AI spend / Total AI spend) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.EXECUTIVE, DashboardLayer.PROGRAM],
        owner_role="CFO",
        data_sources=["finance_system", "erp"],
        tags=["spend", "allocation", "finops"],
    ),
    MetricDefinition(
        metric_id="UC7-004",
        name="Shadow AI Spend Ratio",
        category=MetricCategory.ECONOMIC_VALUE,
        description="Percentage of AI spend outside formal IT budgets and governance",
        formula="(Unattributed AI spend / Total AI spend) × 100",
        unit="percent",
        target=10.0,
        tier1_threshold=10.0,
        tier2_threshold=20.0,
        tier3_threshold=30.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.EXECUTIVE, DashboardLayer.PROGRAM],
        owner_role="CFO",
        data_sources=["cloud_cost", "expense_reports", "api_enumeration"],
        tags=["shadow-ai", "spend", "unbudgeted"],
    ),
    MetricDefinition(
        metric_id="UC7-005",
        name="AI Initiative Ownership Rate",
        category=MetricCategory.ECONOMIC_VALUE,
        description="Percentage of AI initiatives with a single named economic owner",
        formula="(Initiatives with named owner / Total AI initiatives) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CAIO",
        data_sources=["pmo_system", "initiative_charter"],
        tags=["ownership", "accountability", "initiatives"],
    ),
]


# ─── UC-8: Culture, Training & Ethics ───────────────────────────────────────


UC8_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="UC8-001",
        name="Training Completion Rate",
        category=MetricCategory.CULTURE_TRAINING_ETHICS,
        description="Percentage of assigned personnel who completed required AI governance training",
        formula="(Personnel who completed training / Personnel assigned training) × 100",
        unit="percent",
        target=95.0,
        tier1_threshold=85.0,
        tier2_threshold=80.0,
        tier3_threshold=75.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="HR/CAIO",
        data_sources=["lms", "training_matrix"],
        tags=["training", "completion", "culture"],
    ),
    MetricDefinition(
        metric_id="UC8-002",
        name="Assessment Pass Rate",
        category=MetricCategory.CULTURE_TRAINING_ETHICS,
        description="Percentage of personnel who passed AI governance assessments",
        formula="(Personnel who passed / Personnel assessed) × 100",
        unit="percent",
        target=90.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="weekly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="HR/CAIO",
        data_sources=["lms"],
        tags=["assessment", "pass-rate", "competency"],
    ),
    MetricDefinition(
        metric_id="UC8-003",
        name="Awareness Survey Scores",
        category=MetricCategory.CULTURE_TRAINING_ETHICS,
        description="Average score from AI governance awareness surveys",
        formula="AVG(survey_responses) WHERE survey_type = AI_governance_awareness",
        unit="score",
        target=4.0,
        tier1_threshold=4.0,
        tier2_threshold=3.5,
        tier3_threshold=3.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="quarterly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="CAIO",
        data_sources=["survey_platform"],
        tags=["awareness", "survey", "culture"],
    ),
    MetricDefinition(
        metric_id="UC8-004",
        name="Reported Concerns",
        category=MetricCategory.CULTURE_TRAINING_ETHICS,
        description="Count of AI-related concerns reported through whistleblower hotline",
        formula="COUNT(reports WHERE category = AI_related)",
        unit="count",
        target=0.0,
        tier1_threshold=0.0,
        tier2_threshold=5.0,
        tier3_threshold=10.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="Ethics Officer",
        data_sources=["whistleblower_hotline", "ethics_office", "hr"],
        tags=["concerns", "whistleblower", "ethics"],
    ),
]


# ─── AG: Agentic AI Metrics ─────────────────────────────────────────────────


AG_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        metric_id="AG-001",
        name="Goal Accuracy",
        category=MetricCategory.AGENTIC_AI,
        description="Percentage of agent tasks completed successfully without human intervention",
        formula="(Tasks completed successfully / Total tasks attempted) × 100",
        unit="percent",
        target=85.0,
        tier1_threshold=85.0,
        tier2_threshold=75.0,
        tier3_threshold=60.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["agent_telemetry", "langsmith", "langfuse"],
        tags=["agent", "accuracy", "goal"],
    ),
    MetricDefinition(
        metric_id="AG-002",
        name="Plan Adherence",
        category=MetricCategory.AGENTIC_AI,
        description="Percentage of agent actions within approved plan boundaries",
        formula="(Actions within approved plan / Total actions) × 100",
        unit="percent",
        target=95.0,
        tier1_threshold=95.0,
        tier2_threshold=90.0,
        tier3_threshold=80.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["agent_telemetry", "policy_engine"],
        tags=["agent", "plan", "adherence"],
    ),
    MetricDefinition(
        metric_id="AG-003",
        name="Hallucination Rate",
        category=MetricCategory.AGENTIC_AI,
        description="Percentage of agent outputs containing fabricated or unsupported information",
        formula="(Outputs with hallucination / Total outputs evaluated) × 100",
        unit="percent",
        target=1.0,
        tier1_threshold=1.0,
        tier2_threshold=2.0,
        tier3_threshold=5.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="weekly",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["llm_as_judge", "source_verification", "human_review"],
        tags=["agent", "hallucination", "quality"],
    ),
    MetricDefinition(
        metric_id="AG-004",
        name="Human Intervention Rate",
        category=MetricCategory.AGENTIC_AI,
        description="Percentage of agent tasks requiring human escalation or intervention",
        formula="(Tasks with human intervention / Total tasks) × 100",
        unit="percent",
        target=10.0,
        tier1_threshold=20.0,
        tier2_threshold=30.0,
        tier3_threshold=40.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["agent_telemetry"],
        tags=["agent", "intervention", "escalation"],
    ),
    MetricDefinition(
        metric_id="AG-005",
        name="Escalation Frequency",
        category=MetricCategory.AGENTIC_AI,
        description="Number of escalations per 1,000 agent tasks",
        formula="(Total escalations / Total tasks) × 1000",
        unit="per_1000",
        target=50.0,
        tier1_threshold=50.0,
        tier2_threshold=100.0,
        tier3_threshold=200.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["agent_telemetry", "policy_engine"],
        tags=["agent", "escalation", "frequency"],
    ),
    MetricDefinition(
        metric_id="AG-006",
        name="Autonomous Resolution Rate",
        category=MetricCategory.AGENTIC_AI,
        description="Percentage of agent tasks resolved without any human intervention",
        formula="(Tasks resolved autonomously / Total tasks) × 100",
        unit="percent",
        target=80.0,
        tier1_threshold=80.0,
        tier2_threshold=70.0,
        tier3_threshold=50.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["agent_telemetry"],
        tags=["agent", "autonomous", "resolution"],
    ),
    MetricDefinition(
        metric_id="AG-007",
        name="Policy Violation Rate",
        category=MetricCategory.AGENTIC_AI,
        description="Percentage of agent actions violating defined policies",
        formula="(Policy-violating actions / Total actions) × 100",
        unit="percent",
        target=0.5,
        tier1_threshold=0.5,
        tier2_threshold=1.0,
        tier3_threshold=2.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="CISO",
        data_sources=["policy_engine"],
        tags=["agent", "policy", "violation"],
    ),
    MetricDefinition(
        metric_id="AG-008",
        name="Permission Escalation Events",
        category=MetricCategory.AGENTIC_AI,
        description="Count of unauthorized permission increases by agents",
        formula="COUNT(events WHERE event_type = permission_escalation AND authorization = unauthorized)",
        unit="count",
        target=0.0,
        tier1_threshold=0.0,
        tier2_threshold=1.0,
        tier3_threshold=3.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING],
        owner_role="Security",
        data_sources=["agent_iam"],
        tags=["agent", "permission", "escalation"],
    ),
    MetricDefinition(
        metric_id="AG-009",
        name="Tool Abuse Incidents",
        category=MetricCategory.AGENTIC_AI,
        description="Count of agent tool misuse events",
        formula="COUNT(incidents WHERE incident_type = tool_abuse)",
        unit="count",
        target=0.0,
        tier1_threshold=0.0,
        tier2_threshold=1.0,
        tier3_threshold=3.0,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="realtime",
        dashboard_layers=[DashboardLayer.OPERATING],
        owner_role="Security",
        data_sources=["tool_rate_limiting", "parameter_validation", "anomaly_detection"],
        tags=["agent", "tool", "abuse"],
    ),
    MetricDefinition(
        metric_id="AG-010",
        name="Cost per Successful Task",
        category=MetricCategory.AGENTIC_AI,
        description="Average cost per successfully completed agent task",
        formula="Total agent operational cost / Tasks completed successfully",
        unit="usd",
        target=0.50,
        tier1_threshold=0.50,
        tier2_threshold=1.00,
        tier3_threshold=2.50,
        tier1_direction="gt",
        tier2_direction="gt",
        tier3_direction="gt",
        measurement_frequency="daily",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="ML Engineer",
        data_sources=["cloud_billing", "llm_api_usage", "tool_usage"],
        tags=["agent", "cost", "task"],
    ),
    MetricDefinition(
        metric_id="AG-011",
        name="Value Generated per Agent",
        category=MetricCategory.AGENTIC_AI,
        description="Dollar value generated by each agent per period",
        formula="Σ(value_generated_by_agent) / COUNT(active_agents)",
        unit="usd",
        target=1000.0,
        tier1_threshold=500.0,
        tier2_threshold=0.0,
        tier3_threshold=-500.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="monthly",
        dashboard_layers=[DashboardLayer.PROGRAM],
        owner_role="FinOps",
        data_sources=["business_metrics", "agent_telemetry"],
        tags=["agent", "value", "economic"],
    ),
    MetricDefinition(
        metric_id="AG-012",
        name="Agent Identity Coverage",
        category=MetricCategory.AGENTIC_AI,
        description="Percentage of agents with unique identity and named owner",
        formula="(Agents with unique identity AND named owner / Total discovered agents) × 100",
        unit="percent",
        target=100.0,
        tier1_threshold=90.0,
        tier2_threshold=80.0,
        tier3_threshold=70.0,
        tier1_direction="lt",
        tier2_direction="lt",
        tier3_direction="lt",
        measurement_frequency="4h",
        dashboard_layers=[DashboardLayer.OPERATING, DashboardLayer.PROGRAM],
        owner_role="CISO",
        data_sources=["agent_registry", "nhi_vault"],
        tags=["agent", "identity", "coverage"],
    ),
]


# ─── Registry ────────────────────────────────────────────────────────────────


ALL_METRICS: list[MetricDefinition] = (
    UC1_METRICS
    + UC2_METRICS
    + UC3_METRICS
    + UC4_METRICS
    + UC5_METRICS
    + UC6_METRICS
    + UC7_METRICS
    + UC8_METRICS
    + AG_METRICS
)

METRICS_BY_ID: dict[str, MetricDefinition] = {m.metric_id: m for m in ALL_METRICS}

METRICS_BY_CATEGORY: dict[MetricCategory, list[MetricDefinition]] = {
    cat: [m for m in ALL_METRICS if m.category == cat]
    for cat in MetricCategory
}


def get_metric(metric_id: str) -> Optional[MetricDefinition]:
    """Look up a metric definition by ID."""
    return METRICS_BY_ID.get(metric_id)


def get_metrics_by_category(category: MetricCategory) -> list[MetricDefinition]:
    """Get all metrics for a category."""
    return METRICS_BY_CATEGORY.get(category, [])


def get_metrics_by_layer(layer: DashboardLayer) -> list[MetricDefinition]:
    """Get all metrics assigned to a dashboard layer."""
    return [m for m in ALL_METRICS if layer in m.dashboard_layers]


def get_executive_metrics() -> list[MetricDefinition]:
    """Get all metrics for the executive dashboard."""
    return get_metrics_by_layer(DashboardLayer.EXECUTIVE)


def get_program_metrics() -> list[MetricDefinition]:
    """Get all metrics for the program dashboard."""
    return get_metrics_by_layer(DashboardLayer.PROGRAM)


def get_operating_metrics() -> list[MetricDefinition]:
    """Get all metrics for the operating dashboard."""
    return get_metrics_by_layer(DashboardLayer.OPERATING)


def get_agentic_metrics() -> list[MetricDefinition]:
    """Get all agentic AI metrics."""
    return AG_METRICS
