apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cilium-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-manager
spec:
  template:
    metadata:
      annotations:
        io.cilium/bpf: "true"

target:
  kind: Deployment
  name: social-media-manager
