apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-taints-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-manager
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-taints: "dedicated=social-media-manager:NoSchedule"

target:
  kind: Deployment
  name: social-media-manager
