apiVersion: builtin
kind: PatchTransformer
metadata:
  name: polaris-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-manager
spec:
  template:
    metadata:
      annotations:
        polaris.fairwinds.com/injectDapr: "false"

target:
  kind: Deployment
  name: social-media-manager
