export type QuestionnaireFormat = "csv" | "xlsx" | "json" | "pdf";
export type QuestionType = "text" | "boolean" | "select" | "multi_select" | "evidence" | "number";
export type ResponseConfidence = "high" | "medium" | "low";

export interface Questionnaire {
  id: string;
  name: string;
  framework: string;
  format: QuestionnaireFormat;
  questions: Question[];
  importedAt: string;
}

export interface Question {
  id: string;
  number: string;
  category: string;
  question: string;
  type: QuestionType;
  required: boolean;
  options?: string[];
  section?: string;
}

export interface QuestionnaireResponse {
  id: string;
  questionnaireId: string;
  responses: QuestionAnswer[];
  overallConfidence: number;
  completedAt: string;
  autoAnsweredCount: number;
  manualReviewCount: number;
}

export interface QuestionAnswer {
  questionId: string;
  answer: string;
  confidence: ResponseConfidence;
  autoGenerated: boolean;
  evidenceUrls: string[];
  reasoning?: string;
}

export interface KnowledgeBaseEntry {
  id: string;
  category: string;
  keywords: string[];
  answer: string;
  confidence: ResponseConfidence;
  evidenceUrls: string[];
  framework: string;
}

export interface AutomationStats {
  totalQuestionnaires: number;
  totalQuestions: number;
  autoAnsweredRate: number;
  avgConfidence: number;
  timesSaved: number;
}
