apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: video-marketing-restore
spec:
  backupName: video-marketing-backup
  includedNamespaces:
    - video-marketing-prod
  restorePVs: true

target:
  kind: Deployment
  name: video-marketing
