apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: pricing-optimizer-restore
spec:
  backupName: pricing-optimizer-backup
  includedNamespaces:
    - pricing-optimizer-prod
  restorePVs: true

target:
  kind: Deployment
  name: pricing-optimizer
