apiVersion: builtin
kind: PatchTransformer
metadata:
  name: flannel-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-optimizer
spec:
  template:
    metadata:
      annotations:
        flannel.alpha.coreos.com/backend: vxlan

target:
  kind: Deployment
  name: pricing-optimizer
