// Compliance-as-Code engine: parses .grc-policy.yaml and validates org posture

export interface GrcPolicy {
  version: '1' | '2';
  service: string;
  frameworks: string[];
  controls: PolicyControl[];
  data_classification?: 'public' | 'internal' | 'confidential' | 'restricted';
  owner?: string;
}

export interface PolicyControl {
  id: string;
  framework: string;
  satisfied_by: EvidenceSource[];
  required: boolean;
}

export interface EvidenceSource {
  type: 'github_branch_protection' | 'mfa_enabled' | 'vulnerability_scan' | 'training' | 'manual';
  connector?: string;
  max_age_days?: number;
}

export interface PolicyValidationResult {
  service: string;
  status: 'compliant' | 'drifted' | 'unknown';
  controls: ControlResult[];
  drift_count: number;
  generated_at: string;
}

export interface ControlResult {
  control_id: string;
  framework: string;
  required: boolean;
  status: 'satisfied' | 'missing' | 'stale';
  evidence_age_days?: number;
  message: string;
}

export function parsePolicy(yamlContent: string): GrcPolicy {
  // Dynamic import for compatibility
  const yaml = require('js-yaml');
  const raw = yaml.load(yamlContent) as unknown;
  if (
    !raw ||
    typeof raw !== 'object' ||
    !('version' in raw) ||
    !('service' in raw) ||
    !('controls' in raw)
  ) {
    throw new Error('Invalid .grc-policy.yaml: missing required fields (version, service, controls)');
  }
  return raw as GrcPolicy;
}

export function validatePolicy(
  policy: GrcPolicy,
  evidenceRecords: Array<{ control_id: string; framework: string; collected_at: string; evidence_type: string }>
): PolicyValidationResult {
  const now = new Date();
  const results: ControlResult[] = [];

  for (const ctrl of policy.controls) {
    const sources = ctrl.satisfied_by || [];
    let satisfied = false;
    let stale = false;
    let evidenceAgeDays: number | undefined;

    for (const source of sources) {
      const evidence = evidenceRecords.find(e =>
        e.control_id === ctrl.id &&
        e.framework === ctrl.framework &&
        e.evidence_type === source.type
      );
      if (evidence) {
        const age = Math.floor((now.getTime() - new Date(evidence.collected_at).getTime()) / 86400000);
        evidenceAgeDays = age;
        const maxAge = source.max_age_days ?? 90;
        if (age <= maxAge) {
          satisfied = true;
          break;
        } else {
          stale = true;
        }
      }
    }

    results.push({
      control_id: ctrl.id,
      framework: ctrl.framework,
      required: ctrl.required,
      status: satisfied ? 'satisfied' : stale ? 'stale' : 'missing',
      evidence_age_days: evidenceAgeDays,
      message: satisfied
        ? `Control ${ctrl.id} satisfied`
        : stale
          ? `Evidence for ${ctrl.id} is stale (${evidenceAgeDays}d old)`
          : `No evidence found for ${ctrl.id} (${ctrl.framework})`
    });
  }

  const drift = results.filter(r => r.status !== 'satisfied' && r.required);
  return {
    service: policy.service,
    status: drift.length === 0 ? 'compliant' : 'drifted',
    controls: results,
    drift_count: drift.length,
    generated_at: now.toISOString()
  };
}

export function generatePolicyYaml(serviceName: string, frameworks: string[]): string {
  return `# .grc-policy.yaml — generated by GRC Claw
version: '1'
service: ${serviceName}
frameworks: [${frameworks.map(f => `'${f}'`).join(', ')}]
data_classification: internal
owner: security@example.com

controls:
  - id: CC6.1
    framework: SOC2
    required: true
    satisfied_by:
      - type: mfa_enabled
        connector: okta
        max_age_days: 7

  - id: CC8.1
    framework: SOC2
    required: true
    satisfied_by:
      - type: github_branch_protection
        connector: github
        max_age_days: 30

  - id: CC7.2
    framework: SOC2
    required: true
    satisfied_by:
      - type: vulnerability_scan
        max_age_days: 14
`;
}
