apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-configmaps-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-generator
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-configmaps: "content-generator-*"

target:
  kind: Deployment
  name: content-generator
