apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replacement-config
replacements:
  - source:
      kind: ConfigMap
      name: content-generator-config
      fieldPath: data.LOG_LEVEL
    targets:
      - select:
          kind: Deployment
          name: content-generator
        fieldPaths:
          - spec.template.spec.containers.[name=content-generator].env.[name=LOG_LEVEL].value
        options:
          create: true
