apiVersion: builtin
kind: SecretTransformer
metadata:
  name: secret-config
secretGenerator:
  - name: content-generator-secrets
    type: Opaque
    literals:
      - DATABASE_URL=postgresql://prod-db:5432/content-generator
      - API_KEY=prod-api-key
      - JWT_SECRET=prod-jwt-secret
fieldSpecs:
  - path: spec/template/spec/containers/envFrom/secretRef/name
    create: true
