apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sonarqube-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-generator
spec:
  template:
    metadata:
      annotations:
        sonarqube.org/project-key: content-generator

target:
  kind: Deployment
  name: content-generator
