apiVersion: builtin
kind: PatchTransformer
metadata:
  name: envoy-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-enhancer
spec:
  template:
    metadata:
      annotations:
        envoyproxy.io/inject: "true"

target:
  kind: Deployment
  name: crm-enhancer
