apiVersion: builtin
kind: PatchTransformer
metadata:
  name: ikev2-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-enhancer
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: ikev2-conf

target:
  kind: Deployment
  name: crm-enhancer
