apiVersion: builtin
kind: PatchTransformer
metadata:
  name: networkpolicy-patch
patch: |-
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: crm-enhancer-netpol
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: crm-enhancer
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: crm-enhancer-prod
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53

target:
  kind: Deployment
  name: crm-enhancer
