apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replacement-config
replacements:
  - source:
      kind: ConfigMap
      name: crm-enhancer-config
      fieldPath: data.LOG_LEVEL
    targets:
      - select:
          kind: Deployment
          name: crm-enhancer
        fieldPaths:
          - spec.template.spec.containers.[name=crm-enhancer].env.[name=LOG_LEVEL].value
        options:
          create: true
