apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sonarqube-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-enhancer
spec:
  template:
    metadata:
      annotations:
        sonarqube.org/project-key: crm-enhancer

target:
  kind: Deployment
  name: crm-enhancer
