"""gRPC server implementation for GRC_Claw API."""

import asyncio
import hashlib
import time
import uuid
from concurrent import futures
from datetime import datetime, timezone

import grpc

# Import generated protobuf code (generated from proto/grc_claw.proto)
# In production, these would be generated by:
#   python -m grpc_tools.protoc -I./proto --python_out=. --grpc_python_out=. proto/grc_claw.proto
try:
    from app.grpc import grc_claw_pb2, grc_claw_pb2_grpc
except ImportError:
    # Fallback: define stubs for development
    grc_claw_pb2 = None
    grc_claw_pb2_grpc = None

from app.core.config import get_settings

settings = get_settings()


class EnforcementServiceServicer:
    """Enforcement service gRPC servicer."""

    async def Decide(self, request, context):
        """Single enforcement decision."""
        decision_id = f"dec-{uuid.uuid4().hex[:8]}"
        now = datetime.now(timezone.utc)

        # In production, evaluate against policy engine
        verdict = grc_claw_pb2.ALLOW if grc_claw_pb2 else "ALLOW"
        evidence_hash = hashlib.sha256(
            f"{request.agent_id}:{request.action}:{request.resource}".encode()
        ).hexdigest()

        return grc_claw_pb2.DecideResponse(
            decision_id=decision_id,
            request_id=request.request_id,
            verdict=verdict,
            policy_id=request.policy_ids[0] if request.policy_ids else "pol-001",
            policy_version="1.0.0",
            agent_id=request.agent_id,
            action=request.action,
            resource=request.resource,
            evidence_hash=f"sha256:{evidence_hash}",
            timestamp=now.isoformat(),
            ttl_seconds=300,
            signature=f"ecdsa-p256:{hashlib.sha256(decision_id.encode()).hexdigest()[:32]}",
            matched_rules=["allow_read_public"],
            evaluation_time_ms=2.3,
        )

    async def DecideBatch(self, request, context):
        """Batch enforcement decisions."""
        results = []
        allowed = 0
        denied = 0
        total_time = 0.0

        for decide_req in request.decisions:
            decision_id = f"dec-{uuid.uuid4().hex[:8]}"
            now = datetime.now(timezone.utc)
            verdict = grc_claw_pb2.ALLOW if grc_claw_pb2 else "ALLOW"
            eval_time = 2.0

            results.append(grc_claw_pb2.DecideResponse(
                decision_id=decision_id,
                request_id=decide_req.request_id,
                verdict=verdict,
                policy_id=decide_req.policy_ids[0] if decide_req.policy_ids else "pol-001",
                policy_version="1.0.0",
                agent_id=decide_req.agent_id,
                action=decide_req.action,
                resource=decide_req.resource,
                timestamp=now.isoformat(),
                ttl_seconds=300,
                evaluation_time_ms=eval_time,
            ))

            if verdict == grc_claw_pb2.ALLOW:
                allowed += 1
            else:
                denied += 1
            total_time += eval_time

        avg_time = total_time / len(request.decisions) if request.decisions else 0.0

        return grc_claw_pb2.DecideBatchResponse(
            request_id=request.request_id,
            results=results,
            summary=grc_claw_pb2.BatchSummary(
                total=len(request.decisions),
                allowed=allowed,
                denied=denied,
                avg_evaluation_time_ms=avg_time,
            ),
        )

    async def StreamDecisions(self, request_iterator, context):
        """Bidirectional streaming enforcement decisions."""
        async for request in request_iterator:
            decision_id = f"dec-{uuid.uuid4().hex[:8]}"
            now = datetime.now(timezone.utc)

            yield grc_claw_pb2.DecideResponse(
                decision_id=decision_id,
                request_id=request.request_id,
                verdict=grc_claw_pb2.ALLOW if grc_claw_pb2 else "ALLOW",
                policy_id=request.policy_ids[0] if request.policy_ids else "pol-001",
                policy_version="1.0.0",
                agent_id=request.agent_id,
                action=request.action,
                resource=request.resource,
                timestamp=now.isoformat(),
                ttl_seconds=300,
                evaluation_time_ms=2.0,
            )

    async def SubscribeDecisions(self, request, context):
        """Server-streaming: subscribe to decisions for an agent."""
        # In production, this would subscribe to a message broker
        for i in range(100):
            if context.is_active():
                decision_id = f"dec-{uuid.uuid4().hex[:8]}"
                now = datetime.now(timezone.utc)

                yield grc_claw_pb2.DecideResponse(
                    decision_id=decision_id,
                    request_id=f"sub-{i}",
                    verdict=grc_claw_pb2.ALLOW if grc_claw_pb2 else "ALLOW",
                    policy_id="pol-001",
                    policy_version="1.0.0",
                    agent_id=request.agent_id,
                    action="read",
                    resource=f"s3://data/public/file-{i}.csv",
                    timestamp=now.isoformat(),
                    ttl_seconds=300,
                    evaluation_time_ms=2.0,
                )
                await asyncio.sleep(1)
            else:
                break

    async def HealthCheck(self, request, context):
        """Health check."""
        now = datetime.now(timezone.utc)
        return grc_claw_pb2.HealthCheckResponse(
            status=grc_claw_pb2.SERVING if grc_claw_pb2 else "SERVING",
            version=settings.APP_VERSION,
            timestamp=now.isoformat(),
        )


class PolicyServiceServicer:
    """Policy service gRPC servicer."""

    async def GetPolicy(self, request, context):
        """Get a policy by ID."""
        now = datetime.now(timezone.utc)
        return grc_claw_pb2.Policy(
            id=request.policy_id,
            policy_key="AI-ETHICS-001",
            name="Data Access Control Policy",
            description="Controls agent access to data classifications",
            category="privacy",
            status="active",
            version="1.0.0",
            framework_tags=["SOC2", "ISO-27001", "GDPR"],
            owner_id="user-001",
            created_at=now.isoformat(),
            updated_at=now.isoformat(),
            created_by="user-001",
            updated_by="user-001",
        )

    async def ListPolicies(self, request, context):
        """List policies."""
        now = datetime.now(timezone.utc)
        policies = [
            grc_claw_pb2.Policy(
                id=f"pol-{i:03d}",
                policy_key=f"POLICY-{i:03d}",
                name=f"Policy {i}",
                category="safety",
                status="active",
                version="1.0.0",
                created_at=now.isoformat(),
                updated_at=now.isoformat(),
            )
            for i in range(1, min(request.per_page + 1, 11))
        ]

        return grc_claw_pb2.ListPoliciesResponse(
            policies=policies,
            pagination=grc_claw_pb2.Pagination(
                page=request.page,
                per_page=request.per_page,
                total=100,
                total_pages=10,
            ),
        )

    async def CreatePolicy(self, request, context):
        """Create a new policy."""
        now = datetime.now(timezone.utc)
        return grc_claw_pb2.Policy(
            id=f"pol-{uuid.uuid4().hex[:8]}",
            policy_key=request.policy_key,
            name=request.name,
            description=request.description,
            category=request.category,
            status="draft",
            version="1.0.0",
            framework_tags=list(request.framework_tags),
            owner_id="user-001",
            cedar_policy=request.cedar_policy,
            created_at=now.isoformat(),
            updated_at=now.isoformat(),
            created_by="user-001",
            updated_by="user-001",
        )

    async def UpdatePolicy(self, request, context):
        """Update a policy."""
        now = datetime.now(timezone.utc)
        return grc_claw_pb2.Policy(
            id=request.policy_id,
            policy_key="AI-ETHICS-001",
            name=request.name or "Updated Policy",
            description=request.description,
            category="privacy",
            status="active",
            version="1.1.0",
            updated_at=now.isoformat(),
            updated_by="user-001",
        )

    async def DeletePolicy(self, request, context):
        """Delete a policy."""
        return grc_claw_pb2.DeletePolicyResponse(success=True)

    async def CompilePolicy(self, request, context):
        """Compile policy to Rego."""
        now = datetime.now(timezone.utc)
        return grc_claw_pb2.CompilePolicyResponse(
            policy_id=request.policy_id,
            status=grc_claw_pb2.SUCCESS if grc_claw_pb2 else "SUCCESS",
            rego_policy="package grc.agent...\n\ndefault allow := false\n",
            warnings=[],
            errors=[],
            compiled_at=now.isoformat(),
        )

    async def DryRunPolicy(self, request, context):
        """Dry-run policy against test inputs."""
        results = []
        for i, test_input in enumerate(request.test_inputs):
            results.append(grc_claw_pb2.DryRunResult(
                input_index=i,
                decision=grc_claw_pb2.ALLOW if grc_claw_pb2 else "ALLOW",
                matched_rules=["allow_read_public"],
                evaluation_time_ms=2.0,
            ))

        return grc_claw_pb2.DryRunPolicyResponse(
            policy_id=request.policy_id,
            results=results,
            summary=grc_claw_pb2.DryRunSummary(
                total=len(request.test_inputs),
                allowed=len(request.test_inputs),
                denied=0,
                avg_evaluation_time_ms=2.0,
            ),
        )

    async def WatchPolicies(self, request, context):
        """Stream policy changes."""
        for i in range(10):
            if context.is_active():
                now = datetime.now(timezone.utc)
                yield grc_claw_pb2.PolicyChangeEvent(
                    change_type=grc_claw_pb2.CREATED if grc_claw_pb2 else "CREATED",
                    policy=grc_claw_pb2.Policy(
                        id=f"pol-{i}",
                        policy_key=f"POLICY-{i}",
                        name=f"Policy {i}",
                        created_at=now.isoformat(),
                        updated_at=now.isoformat(),
                    ),
                    timestamp=now.isoformat(),
                )
                await asyncio.sleep(5)
            else:
                break


def serve():
    """Start the gRPC server."""
    server = grpc.aio.server(futures.ThreadPoolExecutor(max_workers=settings.GRPC_MAX_WORKERS))

    # Register servicers
    if grc_claw_pb2_grpc:
        grc_claw_pb2_grpc.add_EnforcementServiceServicer_to_server(
            EnforcementServiceServicer(), server
        )
        grc_claw_pb2_grpc.add_PolicyServiceServicer_to_server(
            PolicyServiceServicer(), server
        )

    server.add_insecure_port(f"{settings.GRPC_HOST}:{settings.GRPC_PORT}")
    server.start()
    print(f"gRPC server started on {settings.GRPC_HOST}:{settings.GRPC_PORT}")

    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        server.stop(0)


if __name__ == "__main__":
    serve()
