apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-mig-fan-current-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-optimization
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-mig-fan-current: "0.25"

target:
  kind: Deployment
  name: website-optimization
