apiVersion: v1
kind: Service
metadata:
  name: customer-retention
  labels:
    app: customer-retention
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: customer-retention
