apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: email-marketing-restore
spec:
  backupName: email-marketing-backup
  includedNamespaces:
    - email-marketing-prod
  restorePVs: true

target:
  kind: Deployment
  name: email-marketing
