apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-namespaces-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-namespaces: "default"

target:
  kind: Deployment
  name: email-marketing
