apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: marketing-compliance-restore
spec:
  backupName: marketing-compliance-backup
  includedNamespaces:
    - marketing-compliance-prod
  restorePVs: true

target:
  kind: Deployment
  name: marketing-compliance
