apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-repositories-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-compliance
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-repositories: "repo1"

target:
  kind: Deployment
  name: marketing-compliance
