apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-mig-fan-temperature-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-compliance
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-mig-fan-temperature: "45"

target:
  kind: Deployment
  name: marketing-compliance
