apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-secrets-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-research
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-secrets: "market-research-*"

target:
  kind: Deployment
  name: market-research
