apiVersion: builtin
kind: PatchTransformer
metadata:
  name: nomad-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-research
spec:
  template:
    metadata:
      annotations:
        nomad.hashicorp.com/enable: "true"

target:
  kind: Deployment
  name: market-research
