apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: journey-orchestrator-restore
spec:
  backupName: journey-orchestrator-backup
  includedNamespaces:
    - journey-orchestrator-prod
  restorePVs: true

target:
  kind: Deployment
  name: journey-orchestrator
