apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: namespace-config
namespace: journey-orchestrator-prod
fieldSpecs:
  - path: metadata/namespace
    create: true
  - path: subjects/namespace
    group: rbac.authorization.k8s.io
    kind: RoleBinding
  - path: subjects/namespace
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
