apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sonarqube-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-orchestrator
spec:
  template:
    metadata:
      annotations:
        sonarqube.org/project-key: journey-orchestrator

target:
  kind: Deployment
  name: journey-orchestrator
