apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-management
spec:
  template:
    metadata:
      annotations:
        headscale.io/enable: "true"

target:
  kind: Deployment
  name: feedback-management
