import { randomUUID } from "node:crypto";
import type { Question, QuestionAnswer, KnowledgeBaseEntry, ResponseConfidence } from "../types.js";

// ─── Claude-powered questionnaire answer engine (#4) ──────────────────────────
// When the local knowledge base has no match, calls Claude to synthesize an
// answer from the org's compliance posture context. Produces audit-ready
// responses with confidence scores and evidence references.

interface OrgContext {
  frameworks: string[];        // e.g. ["iso27001", "soc2"]
  controlStatuses?: Record<string, string>;  // controlId → pass/fail
  certifications?: string[];   // e.g. ["SOC 2 Type II certified"]
  orgDescription?: string;     // brief description of what the org does
}

interface ClaudeResponse {
  content: Array<{ type: string; text: string }>;
}

async function callClaudeForAnswer(
  question: Question,
  kbAnswer: KnowledgeBaseEntry | null,
  orgContext: OrgContext,
  apiKey: string,
): Promise<{ answer: string; confidence: ResponseConfidence; reasoning: string }> {
  const systemPrompt = `You are an expert compliance officer filling out a vendor security questionnaire on behalf of your organization.
Your answers should be professional, specific, and accurate based on the organization context provided.
Output ONLY valid JSON: {"answer": "...", "confidence": "high"|"medium"|"low", "reasoning": "..."}
Keep answers concise (2-4 sentences). Be specific about technologies and processes.`;

  const userPrompt = `QUESTIONNAIRE QUESTION:
Category: ${question.category}
Question: ${question.question}
${question.options ? `Options: ${question.options.join(", ")}` : ""}

ORGANIZATION CONTEXT:
Frameworks: ${orgContext.frameworks.join(", ")}
${orgContext.certifications ? `Certifications: ${orgContext.certifications.join(", ")}` : ""}
${orgContext.orgDescription ? `Description: ${orgContext.orgDescription}` : ""}

${kbAnswer ? `KNOWLEDGE BASE MATCH:\n${kbAnswer.answer}` : "No direct knowledge base match — synthesize from context."}

Answer this question professionally and respond with JSON only.`;

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 300,
      system: systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
    }),
    signal: AbortSignal.timeout(20_000),
  });

  if (!res.ok) throw new Error(`Claude API error: ${res.status}`);
  const data = await res.json() as ClaudeResponse;
  const raw = data.content[0]?.text ?? "{}";
  try {
    const cleaned = raw.trim().replace(/^```json?\s*/i, "").replace(/```\s*$/, "");
    return JSON.parse(cleaned) as { answer: string; confidence: ResponseConfidence; reasoning: string };
  } catch {
    return { answer: raw.slice(0, 500), confidence: "low", reasoning: "Parse error — raw AI response" };
  }
}

export class QuestionnaireAnswerEngine {
  private apiKey: string;

  constructor(apiKey?: string) {
    this.apiKey = apiKey ?? process.env.ANTHROPIC_API_KEY ?? "";
  }

  async answerQuestion(
    question: Question,
    kbMatch: KnowledgeBaseEntry | null,
    orgContext: OrgContext,
  ): Promise<QuestionAnswer> {
    // If we have a high-confidence KB match, use it directly
    if (kbMatch && kbMatch.confidence === "high") {
      return {
        questionId: question.id,
        answer: kbMatch.answer,
        confidence: kbMatch.confidence,
        autoGenerated: true,
        evidenceUrls: kbMatch.evidenceUrls,
        reasoning: `Knowledge base match (category: ${kbMatch.category})`,
      };
    }

    // Fall through to Claude for low-confidence or no match
    if (!this.apiKey) {
      return {
        questionId: question.id,
        answer: kbMatch?.answer ?? "Information not available — manual review required.",
        confidence: "low",
        autoGenerated: false,
        evidenceUrls: [],
        reasoning: "No ANTHROPIC_API_KEY set — manual review required",
      };
    }

    try {
      const ai = await callClaudeForAnswer(question, kbMatch, orgContext, this.apiKey);
      return {
        questionId: question.id,
        answer: ai.answer,
        confidence: ai.confidence,
        autoGenerated: true,
        evidenceUrls: kbMatch?.evidenceUrls ?? [],
        reasoning: ai.reasoning,
      };
    } catch (err) {
      return {
        questionId: question.id,
        answer: kbMatch?.answer ?? "Unable to generate answer — manual review required.",
        confidence: "low",
        autoGenerated: false,
        evidenceUrls: [],
        reasoning: `AI error: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  }

  async answerBatch(
    questions: Question[],
    kbMatches: Map<string, KnowledgeBaseEntry | null>,
    orgContext: OrgContext,
    concurrency = 5,
  ): Promise<QuestionAnswer[]> {
    const results: QuestionAnswer[] = [];
    for (let i = 0; i < questions.length; i += concurrency) {
      const batch = questions.slice(i, i + concurrency);
      const answers = await Promise.all(
        batch.map((q) => this.answerQuestion(q, kbMatches.get(q.id) ?? null, orgContext))
      );
      results.push(...answers);
    }
    return results;
  }
}
