import { randomUUID } from "node:crypto";
import type { Questionnaire, Question, QuestionnaireResponse, QuestionAnswer, QuestionType } from "../types.js";
import { QuestionnaireKnowledgeBase } from "./KnowledgeBase.js";

export class QuestionnaireAutomation {
  private kb = new QuestionnaireKnowledgeBase();
  private questionnaires: Map<string, Questionnaire> = new Map();
  private responses: Map<string, QuestionnaireResponse> = new Map();

  parseCSVQuestions(csvContent: string): Questionnaire {
    const lines = csvContent.trim().split("\n");
    const questions: Question[] = [];
    let currentSection = "";

    for (let i = 1; i < lines.length; i++) {
      const cols = lines[i].split(",").map((c) => c.trim());
      if (cols[0] && !cols[1]) { currentSection = cols[0]; continue; }
      if (cols.length < 3) continue;
      questions.push({
        id: randomUUID(),
        number: cols[0],
        category: currentSection || cols[1],
        question: cols[2],
        type: (cols[3] as QuestionType) || "text",
        required: cols[4] !== "false",
        section: currentSection,
      });
    }

    const questionnaire: Questionnaire = {
      id: randomUUID(),
      name: "Imported Questionnaire",
      framework: "custom",
      format: "csv",
      questions,
      importedAt: new Date().toISOString(),
    };
    this.questionnaires.set(questionnaire.id, questionnaire);
    return questionnaire;
  }

  autoAnswer(questionnaireId: string): QuestionnaireResponse | null {
    const questionnaire = this.questionnaires.get(questionnaireId);
    if (!questionnaire) return null;

    const answers: QuestionAnswer[] = [];
    let autoCount = 0;

    for (const q of questionnaire.questions) {
      const match = this.kb.matchQuestion(q.question);
      if (match && match.matchScore >= 3) {
        answers.push({
          questionId: q.id,
          answer: match.entry.answer,
          confidence: match.entry.confidence,
          autoGenerated: true,
          evidenceUrls: match.entry.evidenceUrls,
          reasoning: `Matched via knowledge base (score: ${match.matchScore})`,
        });
        autoCount++;
      } else {
        answers.push({
          questionId: q.id,
          answer: "",
          confidence: "low",
          autoGenerated: false,
          evidenceUrls: [],
          reasoning: "No match found in knowledge base - requires manual review",
        });
      }
    }

    const highConf = answers.filter((a) => a.confidence === "high").length;
    const overallConfidence = Math.round((highConf / answers.length) * 100);

    const response: QuestionnaireResponse = {
      id: randomUUID(),
      questionnaireId,
      responses: answers,
      overallConfidence,
      completedAt: new Date().toISOString(),
      autoAnsweredCount: autoCount,
      manualReviewCount: answers.length - autoCount,
    };
    this.responses.set(response.id, response);
    return response;
  }

  getQuestionnaire(id: string): Questionnaire | undefined { return this.questionnaires.get(id); }
  getResponse(id: string): QuestionnaireResponse | undefined { return this.responses.get(id); }
}
