apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: account-based-marketing-restore
spec:
  backupName: account-based-marketing-backup
  includedNamespaces:
    - account-based-marketing-prod
  restorePVs: true

target:
  kind: Deployment
  name: account-based-marketing
