apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: cross-project-orchestrator-restore
spec:
  backupName: cross-project-orchestrator-backup
  includedNamespaces:
    - cross-project-orchestrator-prod
  restorePVs: true

target:
  kind: Deployment
  name: cross-project-orchestrator
