apiVersion: builtin
kind: PatchTransformer
metadata:
  name: pdb-patch
patch: |-
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cross-project-orchestrator-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cross-project-orchestrator

target:
  kind: Deployment
  name: cross-project-orchestrator
