apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sonarqube-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-project-orchestrator
spec:
  template:
    metadata:
      annotations:
        sonarqube.org/project-key: cross-project-orchestrator

target:
  kind: Deployment
  name: cross-project-orchestrator
