apiVersion: builtin
kind: PatchTransformer
metadata:
  name: toleration-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-project-orchestrator
spec:
  template:
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "cross-project-orchestrator"
          effect: "NoSchedule"

target:
  kind: Deployment
  name: cross-project-orchestrator
