apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replacement-config
replacements:
  - source:
      kind: ConfigMap
      name: customer-retention-config
      fieldPath: data.LOG_LEVEL
    targets:
      - select:
          kind: Deployment
          name: customer-retention
        fieldPaths:
          - spec.template.spec.containers.[name=customer-retention].env.[name=LOG_LEVEL].value
        options:
          create: true
