apiVersion: builtin
kind: PatchTransformer
metadata:
  name: serviceaccount-patch
patch: |-
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-retention-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/customer-retention-role

target:
  kind: Deployment
  name: customer-retention
