{{- if .Values.pepGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pep-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: pep-gateway
spec:
  selector:
    app: pep-gateway
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 9090
      targetPort: 9090
      name: grpc
  type: ClusterIP
{{- end }}
