apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: content-generator-dev

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: content-generator
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: content-generator

configMapGenerator:
  - name: content-generator-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DEBUG=true

commonLabels:
  environment: development

images:
  - name: grcclaw/content-generator
    newTag: dev
