apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-marketing-staging

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: ecommerce-marketing
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: ecommerce-marketing

configMapGenerator:
  - name: ecommerce-marketing-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - DEBUG=false

commonLabels:
  environment: staging

images:
  - name: grcclaw/ecommerce-marketing
    newTag: staging
