apiVersion: builtin
kind: LabelSelectorTransformer
metadata:
  name: label-selector-config
labelSelector:
  matchLabels:
    app.kubernetes.io/name: campaign-optimizer
fieldSpecs:
  - path: spec/selector/matchLabels
    create: true
