apiVersion: builtin
kind: PatchTransformer
metadata:
  name: pdb-patch
patch: |-
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: campaign-optimizer-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: campaign-optimizer

target:
  kind: Deployment
  name: campaign-optimizer
