apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replacement-config
replacements:
  - source:
      kind: ConfigMap
      name: campaign-optimizer-config
      fieldPath: data.LOG_LEVEL
    targets:
      - select:
          kind: Deployment
          name: campaign-optimizer
        fieldPaths:
          - spec.template.spec.containers.[name=campaign-optimizer].env.[name=LOG_LEVEL].value
        options:
          create: true
