apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-pools-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-forecaster
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-pools: "pool-*"

target:
  kind: Deployment
  name: sales-forecaster
