apiVersion: builtin
kind: PatchTransformer
metadata:
  name: renovate-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-forecaster
spec:
  template:
    metadata:
      annotations:
        renovate.enable: "true"

target:
  kind: Deployment
  name: sales-forecaster
