#!/usr/bin/env python3
"""
GRC_Claw Certification Exam Generator
Generates certification exams with randomized questions, adaptive difficulty, and automatic grading.
"""

import json, random, uuid, hashlib, sys
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Optional


class QuestionType(str, Enum):
    MULTIPLE_CHOICE = "multiple_choice"
    MULTI_SELECT = "multi_select"
    TRUE_FALSE = "true_false"
    SCENARIO = "scenario"


class Difficulty(str, Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    EXPERT = "expert"


class CertTrack(str, Enum):
    GRC_FUNDAMENTALS = "grc_fundamentals"
    COMPLIANCE_ANALYST = "compliance_analyst"
    AI_GOVERNANCE = "ai_governance"
    SECURITY_AUDITOR = "security_auditor"
    RISK_MANAGER = "risk_manager"
    ARCHITECT = "grc_architect"


QUESTION_BANK = [
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EASY,"competency":"C1","module_id":"M01","question_text":"What is the default port for the GRC_Claw gateway daemon?","options":["18789","18790","18791","18792"],"correct_answer":"18791","explanation":"The gateway binds to 127.0.0.1:18791 by default.","tags":["gateway","config"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EASY,"competency":"C1","module_id":"M01","question_text":"Which protocol does the GRC_Claw gateway use?","options":["HTTP/1.1","WebSocket","gRPC","MQTT"],"correct_answer":"WebSocket","explanation":"The gateway uses WebSocket with JSON-RPC 2.0.","tags":["gateway","protocol"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M02","question_text":"What are the three planes in GRC_Claw?","options":["Control, Data, Evidence","Input, Process, Output","Frontend, Backend, Database","Management, Operational, Technical"],"correct_answer":"Control, Data, Evidence","explanation":"Control (gateway, agent-runtime), Data (a2z-connector), Evidence (evidence, frameworks).","tags":["architecture"]},
    {"type":QuestionType.TRUE_FALSE,"difficulty":Difficulty.EASY,"competency":"C1","module_id":"M01","question_text":"The gateway supports multiple simultaneous instances per cell.","options":["True","False"],"correct_answer":"False","explanation":"Single instance per cell via lock file.","tags":["gateway"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C2","module_id":"M03","question_text":"Primary function of the agent policy firewall?","options":["Route network traffic","Intercept and enforce allow/deny rules","Monitor resource consumption","Authenticate agents"],"correct_answer":"Intercept and enforce allow/deny rules","explanation":"Intercepts all agent actions and evaluates against policies.","tags":["policy","firewall"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C2","module_id":"M03","question_text":"What happens when trust score drops below threshold?","options":["Agent banned","Agent requires approval","Agent shuts down","Nothing"],"correct_answer":"Agent requires approval","explanation":"Low-trust agents enter supervised mode.","tags":["trust"]},
    {"type":QuestionType.SCENARIO,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","scenario":"Agent with trust score 45 attempts write to /etc/passwd. Policy denies writes outside /tmp/grc-workspace for trust < 60.","question_text":"Outcome?","options":["Allowed","Denied - policy blocks it","Allowed with warning","Queued"],"correct_answer":"Denied - policy blocks it","explanation":"Trust 45 < 60 AND path outside workspace. Both conditions met.","tags":["policy","scenario"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Hash algorithm for evidence integrity?","options":["MD5","SHA-1","SHA-256","SHA-3"],"correct_answer":"SHA-256","explanation":"SHA-256 for content hashing.","tags":["evidence","hashing"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M04","question_text":"Primary purpose of compliance orchestrator?","options":["Generate reports","Chain controls/tests/evidence into workflows","Monitor agents","Manage access"],"correct_answer":"Chain controls/tests/evidence into workflows","explanation":"Chains compliance activities into DAG-based workflows.","tags":["orchestrator"]},
    {"type":QuestionType.MULTI_SELECT,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Valid workflow trigger types? (Select all)","options":["Scheduled (cron)","Event-driven (SIEM)","Manual (user)","Random (probabilistic)","Conditional (state)"],"correct_answer":["Scheduled (cron)","Event-driven (SIEM)","Manual (user)","Conditional (state)"],"explanation":"Supports scheduled, event-driven, manual, conditional. Not random.","tags":["orchestrator","triggers"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Query language for compliance knowledge graph?","options":["SQL","Cypher","SPARQL","GraphQL"],"correct_answer":"Cypher","explanation":"Uses Cypher-like query language.","tags":["knowledge-graph"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Relationship connecting Control to Evidence?","options":["MAPS_TO","TESTS","PRODUCES","DEPENDS_ON"],"correct_answer":"PRODUCES","explanation":"Controls PRODUCES Evidence.","tags":["knowledge-graph"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C5","module_id":"M07","question_text":"Risk score formula?","options":["Likelihood + Impact","Likelihood x Impact x Control Gap","Impact / Likelihood","(Likelihood + Impact) / 2"],"correct_answer":"Likelihood x Impact x Control Gap","explanation":"Product of likelihood, impact, and control gap (0-1).","tags":["risk"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Risk treatment via cyber insurance?","options":["Mitigate","Transfer","Accept","Avoid"],"correct_answer":"Transfer","explanation":"Transfers financial burden to third party.","tags":["risk","treatment"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"BIA stands for?","options":["Business Integration Assessment","Business Impact Analysis","Baseline Infrastructure Audit","Business Intelligence Analytics"],"correct_answer":"Business Impact Analysis","explanation":"Quantifies business impact of disruptions.","tags":["business-impact"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Highest AI model risk classification?","options":["Minimal","Low","High","Unacceptable"],"correct_answer":"Unacceptable","explanation":"Unacceptable models cannot be deployed.","tags":["ai-governance"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"NOT a model risk dimension?","options":["Bias","Explainability","Latency","Robustness"],"correct_answer":"Latency","explanation":"Dimensions: bias, explainability, robustness, data quality.","tags":["ai-governance"]},
    {"type":QuestionType.SCENARIO,"difficulty":Difficulty.EXPERT,"competency":"C8","module_id":"M09","scenario":"AI model shows 15% lower approval rates for a demographic group. Trained on biased historical data.","question_text":"First action?","options":["Retrain with balanced data","Document and escalate to governance board","Adjust threshold","Continue monitoring"],"correct_answer":"Document and escalate to governance board","explanation":"Document and escalate first. Board decides remediation.","tags":["ai-governance","bias","scenario"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C10","module_id":"M08","question_text":"Max acceptable evidence age?","options":["6 months","12 months","18 months","24 months"],"correct_answer":"12 months","explanation":"Evidence must be < 12 months old.","tags":["audit","evidence"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Audit finding lifecycle?","options":["Open to Closed","Open to In Progress to Closed","Identified to Assessed to Remediated to Verified to Closed","New to Assigned to Resolved"],"correct_answer":"Identified to Assessed to Remediated to Verified to Closed","explanation":"5-stage lifecycle.","tags":["audit","findings"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"ZK proof cryptographic system?","options":["zk-STARKs","zk-SNARKs","Bulletproofs","Ring signatures"],"correct_answer":"zk-SNARKs","explanation":"Uses zk-SNARKs for compact proofs.","tags":["zk","cryptography"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C4","module_id":"M05","question_text":"Data flow from SIEM to compliance alert?","options":["SIEM-GW-Evidence-SOC","SIEM-Connector-GW-Evidence-SOC","SIEM-Evidence-GW-SOC","SIEM-Orchestrator-GW-SOC"],"correct_answer":"SIEM-Connector-GW-Evidence-SOC","explanation":"SIEM to A2Z Connector to Gateway to Evidence to SOC Alert.","tags":["integration","a2z"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Threat intelligence format supported?","options":["STIX 1.0","STIX 2.1","OpenIOC","YARA"],"correct_answer":"STIX 2.1","explanation":"Natively supports STIX 2.1.","tags":["threat-intel","stix"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C7","module_id":"M11","question_text":"Threat involving training data manipulation?","options":["Prompt injection","Model extraction","Data poisoning","Adversarial examples"],"correct_answer":"Data poisoning","explanation":"Data poisoning manipulates training data.","tags":["ai-threat"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Trust between federated instances?","options":["Shared API keys","Mutual TLS and trust passports","OAuth 2.0","SSH keys"],"correct_answer":"Mutual TLS and trust passports","explanation":"Mutual TLS for transport, trust passports for identity.","tags":["federation","trust"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C6","module_id":"M13","question_text":"Primary advantage of ZK proofs?","options":["Faster computation","Verify without revealing data","Smaller storage","Easier implementation"],"correct_answer":"Verify without revealing data","explanation":"Verify compliance without exposing sensitive data.","tags":["zk","privacy"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Primary audience for financial governance reports?","options":["SOC analysts","Board and executives","Compliance auditors","IT operations"],"correct_answer":"Board and executives","explanation":"Designed for board and executive consumption.","tags":["financial-governance"]},
    {"type":QuestionType.TRUE_FALSE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Evidence artifacts are mutable.","options":["True","False"],"correct_answer":"False","explanation":"Immutable once created. Updates create new versions.","tags":["evidence","immutability"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EASY,"competency":"C1","module_id":"M01","question_text":"Minimum Node.js version?","options":["Node 16","Node 18","Node 20","Node 22"],"correct_answer":"Node 20","explanation":"Requires Node.js >= 20.","tags":["requirements"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"What is residual risk?","options":["Risk before treatment","Risk remaining after treatment","Risk transferred","Risk eliminated"],"correct_answer":"Risk remaining after treatment","explanation":"Risk remaining after treatment measures.","tags":["risk"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C2","module_id":"M03","question_text":"Purpose of action ledger?","options":["Store conversations","Record agent actions for audit","Track metrics","Manage queues"],"correct_answer":"Record agent actions for audit","explanation":"Immutable record of all agent actions.","tags":["ledger","audit"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Triggers continuous model monitoring alerts?","options":["Daily checks","Metric thresholds exceeded","Manual requests","New deployments"],"correct_answer":"Metric thresholds exceeded","explanation":"Alerts when metrics exceed thresholds.","tags":["ai-governance","monitoring"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Database type for knowledge graph?","options":["Relational","Document","Property graph","Key-value"],"correct_answer":"Property graph","explanation":"Uses property graph model.","tags":["knowledge-graph"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M08","question_text":"Purpose of assurance envelope?","options":["Encrypt evidence","Package evidence with integrity proofs","Compress evidence","Redact data"],"correct_answer":"Package evidence with integrity proofs","explanation":"Packages evidence with cryptographic integrity proofs.","tags":["audit","assurance"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"A2Z SOC endpoint for compliance alerts?","options":["/api/events","/compliance_alerts","/security_events","/background_jobs"],"correct_answer":"/compliance_alerts","explanation":"Alerts pushed to /compliance_alerts.","tags":["a2z","alerts"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C7","module_id":"M11","question_text":"Primary indicator of prompt injection?","options":["Unusual traffic","Attempts to override system instructions","High CPU","Failed logins"],"correct_answer":"Attempts to override system instructions","explanation":"Embedding malicious instructions in user input.","tags":["ai-threat"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Metric for compliance investment return?","options":["Compliance ROI","Risk-adjusted return","Cost per control","Finding reduction rate"],"correct_answer":"Compliance ROI","explanation":"Measures return on compliance investment.","tags":["financial-governance"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"Recommended pipeline implementation order?","options":["Orchestrator-GW-Evidence-Reporting","GW-Evidence-Orchestrator-Reporting","Evidence-GW-Orchestrator-Reporting","Reporting-Orchestrator-GW-Evidence"],"correct_answer":"GW-Evidence-Orchestrator-Reporting","explanation":"Gateway, Evidence, Orchestrator, Reporting.","tags":["architecture","capstone"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Drift detection in continuous compliance?","options":["Detecting posture changes over time","Detecting config changes","Detecting agent anomalies","Detecting tampering"],"correct_answer":"Detecting posture changes over time","explanation":"Monitors compliance posture over time.","tags":["continuous-compliance","drift"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C2","module_id":"M03","question_text":"Component evaluating trust scores?","options":["Policy firewall","Trust score engine","Action ledger","Gateway"],"correct_answer":"Trust score engine","explanation":"Trust score engine evaluates and maintains scores.","tags":["trust"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of threat intel correlation in risk?","options":["Reduce costs","Increase likelihood estimate accuracy","Automate response","Generate reports"],"correct_answer":"Increase likelihood estimate accuracy","explanation":"Grounds likelihood in real-world threat data.","tags":["risk","threat-intel"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"API endpoint for compliance posture?","options":["/api/v1/compliance/posture","/api/v1/controls/status","/api/v1/evidence/summary","/api/v1/audit/status"],"correct_answer":"/api/v1/compliance/posture","explanation":"Exposes /api/v1/compliance/posture.","tags":["api","compliance"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M08","question_text":"Relationship between audit findings and risk register?","options":["Independent","Findings linked to risk entries","Risk entries created from findings","Findings replace risk entries"],"correct_answer":"Findings linked to risk entries","explanation":"Findings can be linked to risk register entries.","tags":["audit","risk"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of model provenance tracking?","options":["Track API usage","Document training data and lineage","Monitor performance","Manage versions"],"correct_answer":"Document training data and lineage","explanation":"Documents complete model lineage.","tags":["ai-governance","provenance"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C4","module_id":"M10","question_text":"Primary benefit of federated mesh?","options":["Reduced costs","Cross-org compliance verification","Faster training","Simpler management"],"correct_answer":"Cross-org compliance verification","explanation":"Enables verification without sharing sensitive data.","tags":["federation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of idempotency cache?","options":["Cache tokens","Prevent duplicate processing","Cache results","Store history"],"correct_answer":"Prevent duplicate processing","explanation":"Prevents duplicate processing via request IDs.","tags":["gateway","idempotency"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M02","question_text":"What is the unified crosswalk?","options":["Network routing table","Mapping between controls across frameworks","Data migration tool","UI component"],"correct_answer":"Mapping between controls across frameworks","explanation":"Maps controls to multiple frameworks simultaneously.","tags":["crosswalk","frameworks"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Primary output of BIA?","options":["Vulnerability list","Financial/operational impact and recovery objectives","Compliance gap report","Risk treatment plan"],"correct_answer":"Financial/operational impact and recovery objectives","explanation":"BIA produces impact estimates and recovery objectives.","tags":["business-impact"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C6","module_id":"M13","question_text":"What is a constraint system in ZK proofs?","options":["Firewall rules","Mathematical representation of computation","Database constraint","Policy rule"],"correct_answer":"Mathematical representation of computation","explanation":"Mathematically represents the computation being proven.","tags":["zk","cryptography"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of IOC-to-control mapping?","options":["Automate ingestion","Correlate threat indicators with controls","Generate reports","Prioritize remediation"],"correct_answer":"Correlate threat indicators with controls","explanation":"Correlates IOCs with compliance controls.","tags":["threat-intel","ioc"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","question_text":"Information in a trust passport?","options":["Conversation history","Cryptographic identity and trust verification","Config settings","Performance metrics"],"correct_answer":"Cryptographic identity and trust verification","explanation":"Contains cryptographic identity and trust data.","tags":["trust","passport"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C5","module_id":"M07","question_text":"Purpose of treatment optimizer?","options":["Fix gaps automatically","Recommend optimal treatment actions","Generate reports","Track progress"],"correct_answer":"Recommend optimal treatment actions","explanation":"Recommends actions based on cost-benefit analysis.","tags":["risk","treatment"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"What is model drift?","options":["Server movement","Performance degradation over time","Model migration","Hyperparameter changes"],"correct_answer":"Performance degradation over time","explanation":"Degradation as input data distribution changes.","tags":["ai-governance","drift"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of evidence completeness reporting?","options":["Measure storage","Identify evidence gaps for audit","Track access patterns","Monitor freshness"],"correct_answer":"Identify evidence gaps for audit","explanation":"Identifies gaps in evidence collection.","tags":["audit","evidence"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"How does federated mesh preserve privacy?","options":["Shared key encryption","Share only hashes and proofs","Trusted third party","Redact fields"],"correct_answer":"Share only hashes and proofs","explanation":"Shares only cryptographic hashes and verification proofs.","tags":["federation","privacy"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of lock file?","options":["Prevent config changes","Ensure single instance per cell","Store tokens","Cache results"],"correct_answer":"Ensure single instance per cell","explanation":"Ensures only one gateway instance per cell.","tags":["gateway","lock"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Difference between scheduled and event-driven triggers?","options":["Speed","Cron schedule vs external events","Reliability","No difference"],"correct_answer":"Cron schedule vs external events","explanation":"Scheduled uses cron; event-driven responds to external events.","tags":["orchestrator","triggers"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"What is the compliance intelligence API?","options":["Natural language interface","REST API exposing graph queries","ML prediction model","Data export tool"],"correct_answer":"REST API exposing graph queries","explanation":"Exposes knowledge graph queries as REST endpoints.","tags":["api","knowledge-graph"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of control gap in risk formula?","options":["Measure cost","Represent control effectiveness (0-1)","Count missing controls","Track progress"],"correct_answer":"Represent control effectiveness (0-1)","explanation":"0 means fully effective, 1 means no controls.","tags":["risk","control-gap"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of trend analysis in financial reports?","options":["Predict costs","Show metrics over time for executives","Identical seasonal patterns","Benchmark"],"correct_answer":"Show metrics over time for executives","explanation":"Shows compliance metrics over time.","tags":["financial-governance","trends"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M14","question_text":"Final step in capstone?","options":["Architecture design","Implementation","Audit simulation","Documentation"],"correct_answer":"Audit simulation","explanation":"Concludes with audit simulation.","tags":["capstone","audit"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C2","module_id":"M03","question_text":"Relationship between policy firewall and action ledger?","options":["Independent","Firewall logs denied actions to ledger","Ledger enforces firewall","Firewall reads policies from ledger"],"correct_answer":"Firewall logs denied actions to ledger","explanation":"Firewall logs all actions to the ledger.","tags":["policy","firewall","ledger"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C7","module_id":"M11","question_text":"Difference between prompt injection and data poisoning?","options":["Same thing","Inference-time vs training-time","Poisoning more dangerous","Injection affects small models"],"correct_answer":"Inference-time vs training-time","explanation":"Prompt injection at inference; data poisoning at training.","tags":["ai-threat"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of model versioning?","options":["Track API versions","Maintain change history for audit/rollback","Manage environments","Optimize performance"],"correct_answer":"Maintain change history for audit/rollback","explanation":"Maintains complete history of model changes.","tags":["ai-governance","versioning"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Benefit of knowledge graph for reporting?","options":["Faster generation","Complex relational queries","Smaller footprint","Simpler UI"],"correct_answer":"Complex relational queries","explanation":"Excels at complex relational queries.","tags":["knowledge-graph","reporting"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"Purpose of A2Z connector?","options":["SOC UI","Bridge GRC_Claw with A2Z SOC","Manage deployments","Store evidence"],"correct_answer":"Bridge GRC_Claw with A2Z SOC","explanation":"Bridges GRC_Claw with the private A2Z SOC.","tags":["a2z","connector"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"C4 model used for?","options":["Compliance framework","Architecture documentation","Risk methodology","Project management"],"correct_answer":"Architecture documentation","explanation":"Documents software architecture at different abstraction levels.","tags":["architecture","c4"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Purpose of framework mapping?","options":["Map network frameworks","Map controls to multiple frameworks","Map roles to permissions","Map agents to tasks"],"correct_answer":"Map controls to multiple frameworks","explanation":"Maps controls to multiple frameworks simultaneously.","tags":["frameworks","mapping"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of cost-benefit analysis in risk treatment?","options":["Minimize all risk","Optimize treatment selection","Eliminate acceptance","Automate decisions"],"correct_answer":"Optimize treatment selection","explanation":"Compares cost of treatment to risk reduction.","tags":["risk","cost-benefit"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of board reporting?","options":["Technical docs","Executive compliance summaries","Automate workflows","Manage evidence"],"correct_answer":"Executive compliance summaries","explanation":"Provides executive-level summaries.","tags":["board","reporting"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Purpose of continuous trust evaluation?","options":["Monitor logins","Assess agent trustworthiness continuously","Evaluate model accuracy","Track training"],"correct_answer":"Assess agent trustworthiness continuously","explanation":"Monitors agent behavior in real-time.","tags":["trust","continuous"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of audit simulation?","options":["Test auditor skills","Verify pipeline effectiveness","Generate fake findings","Train auditors"],"correct_answer":"Verify pipeline effectiveness","explanation":"Tests the complete pipeline's effectiveness.","tags":["audit","simulation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Primary challenge addressed by federated mesh?","options":["Single-tenant limitations","Cross-org verification without data exposure","High costs","Complex management"],"correct_answer":"Cross-org verification without data exposure","explanation":"Solves cross-org verification without data exposure.","tags":["federation","privacy"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of JSON-RPC 2.0?","options":["Data serialization","Standardized method invocation","Authentication","Load balancing"],"correct_answer":"Standardized method invocation","explanation":"Standardized protocol for method invocation over WebSocket.","tags":["gateway","json-rpc"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"What is the DAG-based workflow model?","options":["Directed acyclic graph of steps and dependencies","Data analytics framework","Network topology","Database schema"],"correct_answer":"Directed acyclic graph of steps and dependencies","explanation":"Nodes are steps, edges are dependencies.","tags":["orchestrator","dag"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Entities in compliance knowledge graph?","options":["Users and permissions","Controls, frameworks, evidence, agents, tests","Network devices","Financial transactions"],"correct_answer":"Controls, frameworks, evidence, agents, tests","explanation":"Stores compliance entities and their relationships.","tags":["knowledge-graph","entities"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk register?","options":["Track treatment progress","Record identified risks and status","Store methodologies","Generate reports"],"correct_answer":"Record identified risks and status","explanation":"Comprehensive record of all identified risks.","tags":["risk","register"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance ROI calculation?","options":["Measure productivity","Quantify return on investment","Calculate fees","Benchmark"],"correct_answer":"Quantify return on investment","explanation":"Quantifies return on compliance investment.","tags":["financial-governance","roi"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"Verification key in ZK proof?","options":["Encryption key","Public key to verify proof","Password","Database index"],"correct_answer":"Public key to verify proof","explanation":"Public key used to verify a ZK proof.","tags":["zk","cryptography"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of AI threat detection rules?","options":["Block network traffic","Identify AI-specific threats","Prevent unauthorized access","Monitor performance"],"correct_answer":"Identify AI-specific threats","explanation":"Identifies AI-specific threats in agent interactions.","tags":["ai-threat","detection"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","question_text":"What is the anti-swarm WAF?","options":["Web app firewall","Distributed agent coordination prevention","Network IDS","DDoS protection"],"correct_answer":"Distributed agent coordination prevention","explanation":"Prevents unauthorized distributed agent coordination.","tags":["anti-swarm","waf"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of model registration?","options":["Track API calls","Maintain model registry with metadata","Manage deployment","Monitor performance"],"correct_answer":"Maintain model registry with metadata","explanation":"Maintains comprehensive registry of all AI models.","tags":["ai-governance","registry"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Purpose of compliance intelligence API?","options":["Chat interface","Expose graph queries as REST endpoints","Automate report generation","Manage access"],"correct_answer":"Expose graph queries as REST endpoints","explanation":"Exposes knowledge graph queries as REST endpoints.","tags":["api","knowledge-graph"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"Purpose of org context sync?","options":["Sync org structure and user data","Sync frameworks","Sync agent configs","Sync threat feeds"],"correct_answer":"Sync org structure and user data","explanation":"Synchronizes org structure and user data.","tags":["a2z","org"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"Recommended testing approach?","options":["Test all together","Test each independently before integration","Skip testing","Only test final"],"correct_answer":"Test each independently before integration","explanation":"Each component tested independently before integration.","tags":["capstone","testing"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Purpose of evidence hashing?","options":["Compress storage","Tamper-evident integrity verification","Encrypt transmission","Index retrieval"],"correct_answer":"Tamper-evident integrity verification","explanation":"Provides tamper-evident integrity verification.","tags":["evidence","hashing"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk appetite?","options":["Define max acceptable risk","Measure treatment speed","Calculate premiums","Prioritize findings"],"correct_answer":"Define max acceptable risk","explanation":"Defines maximum risk the organization will accept.","tags":["risk","appetite"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of benchmark comparison?","options":["Compare costs to industry averages","Rank team performance","Evaluate auditors","Measure accuracy"],"correct_answer":"Compare costs to industry averages","explanation":"Compares compliance costs to industry averages.","tags":["financial-governance","benchmark"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Purpose of explainability assessment?","options":["Measure inference speed","Evaluate understandability of decisions","Count parameters","Assess training time"],"correct_answer":"Evaluate understandability of decisions","explanation":"Evaluates how well model decisions can be understood.","tags":["ai-governance","explainability"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of audit planning?","options":["Schedule vacations","Define scope, criteria, schedule","Generate reports","Track findings"],"correct_answer":"Define scope, criteria, schedule","explanation":"Defines scope, criteria, and schedule for audit.","tags":["audit","planning"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Primary benefit for supply chain compliance?","options":["Reduced costs","Verify supplier compliance without accessing sensitive data","Faster training","Simpler management"],"correct_answer":"Verify supplier compliance without accessing sensitive data","explanation":"Enables supply chain verification without accessing sensitive supplier data.","tags":["federation","supply-chain"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of session management?","options":["Store preferences","Manage WebSocket connections","Cache results","Track performance"],"correct_answer":"Manage WebSocket connections","explanation":"Manages WebSocket connections and client sessions.","tags":["gateway","session"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Purpose of escalation rules?","options":["Improve performance","Define actions on failure/timeout","Simplify design","Reduce complexity"],"correct_answer":"Define actions on failure/timeout","explanation":"Defines actions when workflow steps fail or timeout.","tags":["orchestrator","escalation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Purpose of pattern matching?","options":["Optimize performance","Match subgraph patterns for queries","Generate diagrams","Validate integrity"],"correct_answer":"Match subgraph patterns for queries","explanation":"Matches subgraph patterns to answer compliance queries.","tags":["knowledge-graph","pattern-matching"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk ownership assignment?","options":["Distribute risk evenly","Assign responsibility to person/team","Calculate premiums","Prioritize findings"],"correct_answer":"Assign responsibility to person/team","explanation":"Assigns responsibility for each risk.","tags":["risk","ownership"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance cost tracking?","options":["Measure productivity","Track costs for ROI calculation","Calculate fees","Benchmark"],"correct_answer":"Track costs for ROI calculation","explanation":"Tracks cost of compliance activities.","tags":["financial-governance","cost-tracking"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"Purpose of prover in ZK proof?","options":["Verify proof","Generate proof without revealing inputs","Store proof","Encrypt proof"],"correct_answer":"Generate proof without revealing inputs","explanation":"Generates ZK proof without revealing private inputs.","tags":["zk","prover"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of IOC extraction?","options":["Reduce costs","Extract indicators for correlation","Generate reports","Automate response"],"correct_answer":"Extract indicators for correlation","explanation":"Extracts indicators of compromise for correlation.","tags":["threat-intel","ioc"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","question_text":"Purpose of agent collaboration?","options":["Enable agents to work together","Monitor performance","Manage configs","Track locations"],"correct_answer":"Enable agents to work together","explanation":"Enables agents to work together on complex tasks.","tags":["agent","collaboration"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of bias assessment?","options":["Measure inference speed","Evaluate fairness and bias","Count parameters","Assess training time"],"correct_answer":"Evaluate fairness and bias","explanation":"Evaluates fairness and bias in model decisions.","tags":["ai-governance","bias"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Purpose of relationship model?","options":["Optimize performance","Define how entities are connected","Generate diagrams","Validate integrity"],"correct_answer":"Define how entities are connected","explanation":"Defines how compliance entities are connected.","tags":["knowledge-graph","relationships"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"Purpose of event pull mechanism?","options":["Push alerts","Pull security events from SIEM","Sync user data","Manage deployments"],"correct_answer":"Pull security events from SIEM","explanation":"Pulls security events from the SIEM.","tags":["a2z","event-pull"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"Recommended architecture documentation approach?","options":["Informal notes","C4 model for structured documentation","Skip documentation","Only diagrams"],"correct_answer":"C4 model for structured documentation","explanation":"C4 model provides structured architecture documentation.","tags":["capstone","documentation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Purpose of control test references?","options":["Link controls to tests","Track progress","Calculate costs","Generate reports"],"correct_answer":"Link controls to tests","explanation":"Links controls to their implementation tests.","tags":["controls","tests"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk monitoring?","options":["Track treatment progress","Continuously monitor risk indicators","Calculate scores","Generate reports"],"correct_answer":"Continuously monitor risk indicators","explanation":"Continuously monitors risk indicators and triggers.","tags":["risk","monitoring"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance investment analysis?","options":["Measure productivity","Analyze investment effectiveness","Calculate fees","Benchmark"],"correct_answer":"Analyze investment effectiveness","explanation":"Analyzes effectiveness of compliance investments.","tags":["financial-governance","investment"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Purpose of model lineage tracking?","options":["Track API usage","Document complete development history","Monitor performance","Manage configs"],"correct_answer":"Document complete development history","explanation":"Documents complete history of model development.","tags":["ai-governance","lineage"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of audit criteria mapping?","options":["Map criteria to controls and evidence","Schedule activities","Generate reports","Track findings"],"correct_answer":"Map criteria to controls and evidence","explanation":"Maps audit criteria to controls and evidence requirements.","tags":["audit","criteria"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Primary benefit for supply chain risk management?","options":["Reduced costs","Verify supplier risk posture without accessing sensitive data","Faster training","Simpler management"],"correct_answer":"Verify supplier risk posture without accessing sensitive data","explanation":"Enables supply chain risk management without accessing sensitive data.","tags":["federation","supply-chain"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of gateway routing?","options":["Route network traffic","Route tool calls to agent runtime","Route requests to reports","Route evidence to storage"],"correct_answer":"Route tool calls to agent runtime","explanation":"Routes tool calls to the appropriate agent runtime.","tags":["gateway","routing"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Purpose of workflow timeouts?","options":["Improve performance","Prevent indefinite execution","Simplify design","Reduce complexity"],"correct_answer":"Prevent indefinite execution","explanation":"Prevents workflow steps from running indefinitely.","tags":["orchestrator","timeout"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Purpose of subgraph matching?","options":["Optimize performance","Match specific entity/relationship patterns","Generate diagrams","Validate integrity"],"correct_answer":"Match specific entity/relationship patterns","explanation":"Matches specific patterns of entities and relationships.","tags":["knowledge-graph","subgraph"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk reporting?","options":["Track treatment progress","Communicate risk status to stakeholders","Calculate scores","Generate findings"],"correct_answer":"Communicate risk status to stakeholders","explanation":"Communicates risk status to stakeholders.","tags":["risk","reporting"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance budget allocation?","options":["Distribute evenly","Allocate based on risk priorities","Calculate fees","Measure productivity"],"correct_answer":"Allocate based on risk priorities","explanation":"Allocates budget based on risk priorities.","tags":["financial-governance","budget"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"Purpose of verifier in ZK proof?","options":["Generate proof","Verify proof using verification key and public inputs","Store proof","Encrypt proof"],"correct_answer":"Verify proof using verification key and public inputs","explanation":"Verifies the proof using the verification key and public inputs.","tags":["zk","verifier"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of threat intelligence ingestion?","options":["Reduce costs","Import and process threat feeds for correlation","Generate reports","Automate response"],"correct_answer":"Import and process threat feeds for correlation","explanation":"Imports and processes threat intelligence feeds.","tags":["threat-intel","ingestion"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","question_text":"Purpose of agent identity management?","options":["Track locations","Manage agent identities and authentication","Monitor performance","Manage configs"],"correct_answer":"Manage agent identities and authentication","explanation":"Manages agent identities and authentication.","tags":["agent","identity"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of model metadata management?","options":["Track API usage","Manage model metadata including version and provenance","Monitor performance","Manage configs"],"correct_answer":"Manage model metadata including version and provenance","explanation":"Manages model metadata.","tags":["ai-governance","metadata"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Purpose of entity model?","options":["Optimize performance","Define entity types and properties","Generate diagrams","Validate integrity"],"correct_answer":"Define entity types and properties","explanation":"Defines types of compliance entities and their properties.","tags":["knowledge-graph","entities"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"Purpose of alert push mechanism?","options":["Pull events","Push compliance alerts to SOC","Sync user data","Manage deployments"],"correct_answer":"Push compliance alerts to SOC","explanation":"Pushes compliance alerts to the SOC notification system.","tags":["a2z","alert-push"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"Recommended integration testing approach?","options":["Test all together","Test independently then integrated","Skip testing","Only test final"],"correct_answer":"Test independently then integrated","explanation":"Test each component independently, then test integrated components.","tags":["capstone","integration-testing"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Purpose of evidence metadata?","options":["Compress storage","Provide context and verification info","Encrypt transmission","Index retrieval"],"correct_answer":"Provide context and verification info","explanation":"Provides context and verification information.","tags":["evidence","metadata"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk assessment automation?","options":["Eliminate risk assessors","Automate risk data collection and analysis","Generate reports","Track progress"],"correct_answer":"Automate risk data collection and analysis","explanation":"Automates collection and analysis of risk data.","tags":["risk","automation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance effectiveness measurement?","options":["Measure productivity","Measure effectiveness of controls and activities","Calculate fees","Benchmark"],"correct_answer":"Measure effectiveness of controls and activities","explanation":"Measures effectiveness of compliance controls.","tags":["financial-governance","effectiveness"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Purpose of model retirement?","options":["Delete files","Decommission models not meeting standards","Archive versions","Transfer teams"],"correct_answer":"Decommission models not meeting standards","explanation":"Decommissions models that no longer meet standards.","tags":["ai-governance","retirement"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of audit finding remediation tracking?","options":["Track assignments","Track corrective action implementation","Generate reports","Schedule activities"],"correct_answer":"Track corrective action implementation","explanation":"Tracks implementation of corrective actions.","tags":["audit","remediation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Primary benefit for regulatory compliance?","options":["Reduced costs","Demonstrate compliance without exposing sensitive data","Faster training","Simpler management"],"correct_answer":"Demonstrate compliance without exposing sensitive data","explanation":"Enables compliance demonstration without exposing sensitive data.","tags":["federation","regulatory"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of job management?","options":["Manage job applications","Manage background jobs and scheduled tasks","Track performance","Store results"],"correct_answer":"Manage background jobs and scheduled tasks","explanation":"Manages background jobs and scheduled tasks.","tags":["gateway","jobs"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Purpose of conditional branching?","options":["Improve performance","Enable different execution paths","Simplify design","Reduce complexity"],"correct_answer":"Enable different execution paths","explanation":"Enables different execution paths based on conditions.","tags":["orchestrator","branching"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Purpose of graph indexing?","options":["Optimize query performance","Generate diagrams","Validate integrity","Store preferences"],"correct_answer":"Optimize query performance","explanation":"Optimizes query performance.","tags":["knowledge-graph","indexing"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk assessment prioritization?","options":["Distribute evenly","Prioritize by score and business impact","Calculate premiums","Generate reports"],"correct_answer":"Prioritize by score and business impact","explanation":"Prioritizes risks based on score and business impact.","tags":["risk","prioritization"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance trend analysis?","options":["Predict costs","Analyze metrics over time","Identical patterns","Benchmark"],"correct_answer":"Analyze metrics over time","explanation":"Analyzes compliance metrics over time.","tags":["financial-governance","trends"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"Purpose of setup phase in ZK proof?","options":["Generate proof","Generate proving and verification keys","Verify proof","Store proof"],"correct_answer":"Generate proving and verification keys","explanation":"Generates the proving and verification keys.","tags":["zk","setup"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of threat intelligence correlation?","options":["Reduce costs","Correlate multiple feeds for comprehensive picture","Generate reports","Automate response"],"correct_answer":"Correlate multiple feeds for comprehensive picture","explanation":"Correlates multiple threat feeds.","tags":["threat-intel","correlation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","question_text":"Purpose of agent task management?","options":["Track locations","Manage task assignment and execution","Monitor performance","Manage configs"],"correct_answer":"Manage task assignment and execution","explanation":"Manages assignment and execution of tasks to agents.","tags":["agent","task-management"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of model deployment management?","options":["Track API usage","Manage deployment to production","Monitor performance","Manage configs"],"correct_answer":"Manage deployment to production","explanation":"Manages deployment of models to production.","tags":["ai-governance","deployment"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Purpose of query optimization?","options":["Improve performance via indexing and caching","Generate diagrams","Validate integrity","Store preferences"],"correct_answer":"Improve performance via indexing and caching","explanation":"Improves query performance through indexing and caching.","tags":["knowledge-graph","optimization"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"Purpose of org sync?","options":["Sync org structure and user data","Sync frameworks","Sync agent configs","Sync threat feeds"],"correct_answer":"Sync org structure and user data","explanation":"Synchronizes org structure and user data.","tags":["a2z","org-sync"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"Recommended documentation approach?","options":["Informal notes","C4 model for structured documentation","Skip documentation","Only diagrams"],"correct_answer":"C4 model for structured documentation","explanation":"C4 model provides structured documentation.","tags":["capstone","documentation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Purpose of evidence verification?","options":["Compress storage","Verify integrity and authenticity","Encrypt transmission","Index retrieval"],"correct_answer":"Verify integrity and authenticity","explanation":"Verifies integrity and authenticity of evidence.","tags":["evidence","verification"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk treatment verification?","options":["Track progress","Verify treatment measures are effective","Calculate scores","Generate reports"],"correct_answer":"Verify treatment measures are effective","explanation":"Verifies that risk treatment measures are effective.","tags":["risk","verification"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance ROI reporting?","options":["Measure productivity","Report return on investment to stakeholders","Calculate fees","Benchmark"],"correct_answer":"Report return on investment to stakeholders","explanation":"Reports return on compliance investment.","tags":["financial-governance","roi"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Purpose of model monitoring in production?","options":["Track API usage","Monitor performance and behavior in production","Manage configs","Manage deployments"],"correct_answer":"Monitor performance and behavior in production","explanation":"Monitors model performance and behavior in production.","tags":["ai-governance","monitoring"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of audit evidence collection?","options":["Compress storage","Collect and verify evidence for audit criteria","Encrypt transmission","Index retrieval"],"correct_answer":"Collect and verify evidence for audit criteria","explanation":"Collects and verifies evidence for audit criteria.","tags":["audit","evidence"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Primary benefit for multi-tenant environments?","options":["Reduced costs","Enable verification across tenants without data exposure","Faster training","Simpler management"],"correct_answer":"Enable verification across tenants without data exposure","explanation":"Enables verification across tenants without data exposure.","tags":["federation","multi-tenant"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of gateway authentication?","options":["Encrypt data in transit","Verify client identity","Authorize actions","Sign evidence"],"correct_answer":"Verify client identity","explanation":"Verifies identity of clients connecting to the gateway.","tags":["gateway","authentication"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Purpose of workflow monitoring?","options":["Improve performance","Monitor execution and detect issues","Simplify design","Reduce complexity"],"correct_answer":"Monitor execution and detect issues","explanation":"Monitors workflow execution and detects issues.","tags":["orchestrator","monitoring"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Purpose of graph visualization?","options":["Optimize performance","Visualize entities and relationships","Validate integrity","Store preferences"],"correct_answer":"Visualize entities and relationships","explanation":"Visualizes compliance entities and relationships.","tags":["knowledge-graph","visualization"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk assessment reporting?","options":["Track progress","Communicate assessment results to stakeholders","Calculate scores","Generate findings"],"correct_answer":"Communicate assessment results to stakeholders","explanation":"Communicates risk assessment results to stakeholders.","tags":["risk","reporting"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance investment tracking?","options":["Measure productivity","Track investments and outcomes","Calculate fees","Benchmark"],"correct_answer":"Track investments and outcomes","explanation":"Tracks compliance investments and their outcomes.","tags":["financial-governance","investment"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"Purpose of proving key?","options":["Verify proof","Generate proof","Store proof","Encrypt proof"],"correct_answer":"Generate proof","explanation":"Used by the prover to generate the ZK proof.","tags":["zk","proving-key"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of threat intelligence processing?","options":["Reduce costs","Process and normalize threat intel for correlation","Generate reports","Automate response"],"correct_answer":"Process and normalize threat intel for correlation","explanation":"Processes and normalizes threat intelligence.","tags":["threat-intel","processing"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","question_text":"Purpose of agent policy management?","options":["Track locations","Manage policies governing agent behavior","Monitor performance","Manage configs"],"correct_answer":"Manage policies governing agent behavior","explanation":"Manages policies that govern agent behavior.","tags":["agent","policy"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of model risk classification?","options":["Measure inference speed","Classify models by risk level","Count parameters","Assess training time"],"correct_answer":"Classify models by risk level","explanation":"Classifies models by risk level for governance.","tags":["ai-governance","risk-classification"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Purpose of schema?","options":["Optimize performance","Define knowledge graph structure","Generate diagrams","Validate integrity"],"correct_answer":"Define knowledge graph structure","explanation":"Defines the structure of the knowledge graph.","tags":["knowledge-graph","schema"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"Purpose of compliance check?","options":["Run compliance checks on schedule","Pull events from SIEM","Push alerts to SOC","Sync user data"],"correct_answer":"Run compliance checks on schedule","explanation":"Runs compliance checks on a schedule.","tags":["a2z","compliance-check"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"Recommended architecture design approach?","options":["Informal notes","C4 model for structured design","Skip design","Only diagrams"],"correct_answer":"C4 model for structured design","explanation":"C4 model provides structured architecture design.","tags":["capstone","architecture"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Purpose of evidence lifecycle management?","options":["Compress storage","Manage lifecycle from creation to archival","Encrypt transmission","Index retrieval"],"correct_answer":"Manage lifecycle from creation to archival","explanation":"Manages the lifecycle of evidence.","tags":["evidence","lifecycle"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk assessment scheduling?","options":["Distribute evenly","Schedule regular risk assessments","Calculate premiums","Generate reports"],"correct_answer":"Schedule regular risk assessments","explanation":"Schedules regular risk assessments.","tags":["risk","scheduling"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance cost analysis?","options":["Measure productivity","Analyze cost of compliance activities","Calculate fees","Benchmark"],"correct_answer":"Analyze cost of compliance activities","explanation":"Analyzes the cost of compliance activities.","tags":["financial-governance","cost-analysis"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Purpose of model compliance verification?","options":["Track API usage","Verify models comply with governance policies","Monitor performance","Manage configs"],"correct_answer":"Verify models comply with governance policies","explanation":"Verifies that models comply with governance policies.","tags":["ai-governance","compliance"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of audit preparation?","options":["Schedule vacations","Prepare evidence and documentation for audit","Generate reports","Track findings"],"correct_answer":"Prepare evidence and documentation for audit","explanation":"Prepares evidence and documentation for audit.","tags":["audit","preparation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Primary benefit for supply chain risk management?","options":["Reduced costs","Verify supplier risk posture without accessing sensitive data","Faster training","Simpler management"],"correct_answer":"Verify supplier risk posture without accessing sensitive data","explanation":"Enables supply chain risk management without accessing sensitive data.","tags":["federation","supply-chain"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of gateway authorization?","options":["Encrypt data in transit","Verify client permissions","Authenticate clients","Sign evidence"],"correct_answer":"Verify client permissions","explanation":"Verifies client permissions for specific operations.","tags":["gateway","authorization"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Purpose of workflow versioning?","options":["Improve performance","Manage different versions of workflow definitions","Simplify design","Reduce complexity"],"correct_answer":"Manage different versions of workflow definitions","explanation":"Manages different versions of workflow definitions.","tags":["orchestrator","versioning"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Purpose of graph analytics?","options":["Optimize performance","Analyze compliance patterns and trends","Validate integrity","Store preferences"],"correct_answer":"Analyze compliance patterns and trends","explanation":"Analyzes compliance patterns and trends.","tags":["knowledge-graph","analytics"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk assessment documentation?","options":["Track progress","Document methodology and results","Calculate scores","Generate reports"],"correct_answer":"Document methodology and results","explanation":"Documents risk assessment methodology and results.","tags":["risk","documentation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance budget planning?","options":["Distribute evenly","Plan budget based on risk priorities","Calculate fees","Measure productivity"],"correct_answer":"Plan budget based on risk priorities","explanation":"Plans compliance budget based on risk priorities.","tags":["financial-governance","budget"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"Purpose of common reference string?","options":["Generate proof","Provide shared parameters for proof generation and verification","Verify proof","Store proof"],"correct_answer":"Provide shared parameters for proof generation and verification","explanation":"Provides shared parameters for proof generation and verification.","tags":["zk","crs"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of threat intelligence normalization?","options":["Reduce costs","Normalize from different formats for correlation","Generate reports","Automate response"],"correct_answer":"Normalize from different formats for correlation","explanation":"Normalizes threat intelligence from different formats.","tags":["threat-intel","normalization"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C2","module_id":"M03","question_text":"Purpose of agent supervision?","options":["Track locations","Monitor and control agent actions under policy","Monitor performance","Manage configs"],"correct_answer":"Monitor and control agent actions under policy","explanation":"Monitors and controls agent actions under policy.","tags":["agent","supervision"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C8","module_id":"M09","question_text":"Purpose of model governance?","options":["Track API usage","Govern AI models throughout lifecycle","Monitor performance","Manage configs"],"correct_answer":"Govern AI models throughout lifecycle","explanation":"Governs AI models throughout their lifecycle.","tags":["ai-governance","lifecycle"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C6","module_id":"M06","question_text":"Purpose of data model?","options":["Optimize performance","Define how compliance data is structured","Generate diagrams","Validate integrity"],"correct_answer":"Define how compliance data is structured","explanation":"Defines how compliance data is structured and stored.","tags":["knowledge-graph","data-model"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C4","module_id":"M05","question_text":"Purpose of event mapping?","options":["Map security events to compliance controls","Pull events from SIEM","Push alerts to SOC","Sync user data"],"correct_answer":"Map security events to compliance controls","explanation":"Maps security events to compliance controls.","tags":["a2z","event-mapping"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C1","module_id":"M14","question_text":"Recommended architecture design approach?","options":["Informal notes","C4 model for structured design","Skip design","Only diagrams"],"correct_answer":"C4 model for structured design","explanation":"C4 model provides structured architecture design.","tags":["capstone","architecture"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C3","module_id":"M02","question_text":"Purpose of evidence retention?","options":["Compress storage","Retain evidence for compliance and audit","Encrypt transmission","Index retrieval"],"correct_answer":"Retain evidence for compliance and audit","explanation":"Retains evidence for compliance and audit requirements.","tags":["evidence","retention"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk assessment review?","options":["Track progress","Review and update assessments periodically","Calculate scores","Generate reports"],"correct_answer":"Review and update assessments periodically","explanation":"Reviews and updates risk assessments periodically.","tags":["risk","review"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance investment optimization?","options":["Measure productivity","Optimize investments for maximum risk reduction","Calculate fees","Benchmark"],"correct_answer":"Optimize investments for maximum risk reduction","explanation":"Optimizes compliance investments.","tags":["financial-governance","optimization"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C8","module_id":"M09","question_text":"Purpose of model audit?","options":["Track API usage","Audit model compliance with governance policies","Monitor performance","Manage configs"],"correct_answer":"Audit model compliance with governance policies","explanation":"Audits model compliance with governance policies.","tags":["ai-governance","audit"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C10","module_id":"M08","question_text":"Purpose of audit execution?","options":["Schedule vacations","Execute audit plan and collect evidence","Generate reports","Track findings"],"correct_answer":"Execute audit plan and collect evidence","explanation":"Executes the audit plan and collects evidence.","tags":["audit","execution"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C4","module_id":"M10","question_text":"Primary benefit for regulatory reporting?","options":["Reduced costs","Enable regulatory reporting without exposing sensitive data","Faster training","Simpler management"],"correct_answer":"Enable regulatory reporting without exposing sensitive data","explanation":"Enables regulatory reporting without exposing sensitive data.","tags":["federation","regulatory"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C1","module_id":"M01","question_text":"Purpose of gateway logging?","options":["Store preferences","Log operations for audit and debugging","Cache results","Track performance"],"correct_answer":"Log operations for audit and debugging","explanation":"Logs gateway operations for audit and debugging.","tags":["gateway","logging"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C3","module_id":"M04","question_text":"Purpose of workflow optimization?","options":["Improve performance and efficiency","Manage versions","Simplify design","Reduce complexity"],"correct_answer":"Improve performance and efficiency","explanation":"Improves workflow performance and efficiency.","tags":["orchestrator","optimization"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C6","module_id":"M06","question_text":"Purpose of graph querying?","options":["Optimize performance","Query knowledge graph for compliance info","Validate integrity","Store preferences"],"correct_answer":"Query knowledge graph for compliance info","explanation":"Queries the knowledge graph for compliance information.","tags":["knowledge-graph","querying"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.HARD,"competency":"C5","module_id":"M07","question_text":"Purpose of risk assessment validation?","options":["Track progress","Validate results for accuracy and completeness","Calculate scores","Generate reports"],"correct_answer":"Validate results for accuracy and completeness","explanation":"Validates risk assessment results.","tags":["risk","validation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C9","module_id":"M12","question_text":"Purpose of compliance investment evaluation?","options":["Measure productivity","Evaluate effectiveness of investments","Calculate fees","Benchmark"],"correct_answer":"Evaluate effectiveness of investments","explanation":"Evaluates effectiveness of compliance investments.","tags":["financial-governance","evaluation"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.EXPERT,"competency":"C10","module_id":"M13","question_text":"Purpose of trusted setup?","options":["Generate proof","Generate proving and verification keys in secure environment","Verify proof","Store proof"],"correct_answer":"Generate proving and verification keys in secure environment","explanation":"Generates keys in a secure environment.","tags":["zk","trusted-setup"]},
    {"type":QuestionType.MULTIPLE_CHOICE,"difficulty":Difficulty.MEDIUM,"competency":"C7","module_id":"M11","question_text":"Purpose of threat intelligence enrichment?","options":["Reduce costs","Enrich threat intel with additional context","Generate reports","Automate response"],"correct_answer":"Enrich threat intel with additional context","explanation":"Enriches threat intelligence with additional context.","tags":["threat-intel","enrichment"]},
]

TRACK_CONFIG = {
    CertTrack.GRC_FUNDAMENTALS: {"name": "GRC Fundamentals", "description": "Foundational GRC_Claw concepts", "competencies": ["C1", "C2", "C3"], "modules": ["M01", "M02", "M03", "M04"], "num_questions": 20, "passing_score": 70.0, "time_limit_minutes": 30, "validity_months": 12},
    CertTrack.COMPLIANCE_ANALYST: {"name": "Compliance Analyst", "description": "Compliance operations and evidence", "competencies": ["C3", "C6", "C10"], "modules": ["M02", "M04", "M06", "M08"], "num_questions": 25, "passing_score": 75.0, "time_limit_minutes": 45, "validity_months": 12},
    CertTrack.AI_GOVERNANCE: {"name": "AI Governance", "description": "AI model governance and risk", "competencies": ["C2", "C5", "C8"], "modules": ["M03", "M07", "M09"], "num_questions": 25, "passing_score": 75.0, "time_limit_minutes": 45, "validity_months": 12},
    CertTrack.SECURITY_AUDITOR: {"name": "Security Auditor", "description": "Audit management and assurance", "competencies": ["C1", "C3", "C10"], "modules": ["M02", "M08", "M13"], "num_questions": 30, "passing_score": 80.0, "time_limit_minutes": 60, "validity_months": 12},
    CertTrack.RISK_MANAGER: {"name": "Risk Manager", "description": "Risk assessment and treatment", "competencies": ["C5", "C9"], "modules": ["M07", "M12"], "num_questions": 25, "passing_score": 75.0, "time_limit_minutes": 45, "validity_months": 12},
    CertTrack.ARCHITECT: {"name": "GRC Architect", "description": "Advanced architecture and federation", "competencies": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10"], "modules": ["M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09", "M10", "M11", "M12", "M13", "M14"], "num_questions": 40, "passing_score": 80.0, "time_limit_minutes": 90, "validity_months": 24},
}


class ExamGenerator:
    def __init__(self, data_dir="~/.grc_claw/certification"):
        self.data_dir = Path(data_dir).expanduser()
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.results_file = self.data_dir / "exam_results.json"
        self.results = self._load_results()

    def _load_results(self):
        if self.results_file.exists():
            with open(self.results_file) as f:
                return json.load(f)
        return {}

    def _save_results(self):
        with open(self.results_file, "w") as f:
            json.dump(self.results, f, indent=2)

    def generate_exam(self, track, user_id, seed=None):
        config = TRACK_CONFIG[track]
        rng = random.Random(seed or hash(user_id + track.value))
        eligible = [q for q in QUESTION_BANK if q["competency"] in config["competencies"]]
        if len(eligible) < config["num_questions"]:
            eligible = QUESTION_BANK
        num_q = config["num_questions"]
        easy_count = int(num_q * 0.25)
        medium_count = int(num_q * 0.35)
        hard_count = int(num_q * 0.25)
        expert_count = num_q - easy_count - medium_count - hard_count
        selected = []
        for diff, count in [(Difficulty.EASY, easy_count), (Difficulty.MEDIUM, medium_count), (Difficulty.HARD, hard_count), (Difficulty.EXPERT, expert_count)]:
            pool = [q for q in eligible if q["difficulty"] == diff]
            if len(pool) < count:
                pool = [q for q in eligible if q["difficulty"] == diff] or eligible
            selected.extend(rng.sample(pool, min(count, len(pool))))
        rng.shuffle(selected)
        questions = []
        for i, q in enumerate(selected):
            q_copy = dict(q)
            q_copy["question_id"] = "Q{:03d}".format(i + 1)
            diff_val = q["difficulty"].value if isinstance(q["difficulty"], Difficulty) else q["difficulty"]
            q_copy["points"] = {"easy": 1, "medium": 2, "hard": 3, "expert": 4}[diff_val]
            questions.append(q_copy)
        exam_id = str(uuid.uuid4())
        return {"exam_id": exam_id, "track": track.value, "track_name": config["name"], "user_id": user_id, "generated_at": datetime.now().isoformat(), "time_limit_minutes": config["time_limit_minutes"], "passing_score": config["passing_score"], "total_questions": len(questions), "total_points": sum(q["points"] for q in questions), "questions": questions}

    def grade_exam(self, exam, answers, time_taken_minutes):
        question_results = []
        total_points = 0
        earned_points = 0
        competency_points = {}
        competency_earned = {}
        for q in exam["questions"]:
            qid = q["question_id"]
            correct = q["correct_answer"]
            user_answer = answers.get(qid, "")
            points = q["points"]
            total_points += points
            comp = q["competency"]
            competency_points[comp] = competency_points.get(comp, 0) + points
            if isinstance(correct, list):
                if isinstance(user_answer, list):
                    is_correct = set(correct) == set(user_answer)
                else:
                    is_correct = False
            else:
                is_correct = str(user_answer).strip().lower() == str(correct).strip().lower()
            if is_correct:
                earned_points += points
                competency_earned[comp] = competency_earned.get(comp, 0) + points
            question_results.append({"question_id": qid, "competency": comp, "module_id": q["module_id"], "difficulty": q["difficulty"], "user_answer": user_answer, "correct_answer": correct, "is_correct": is_correct, "points_earned": points if is_correct else 0, "points_possible": points, "explanation": q["explanation"]})
        score_pct = round(earned_points / total_points * 100, 1) if total_points > 0 else 0
        passed = score_pct >= exam["passing_score"]
        competency_scores = {}
        for comp in competency_points:
            competency_scores[comp] = round(competency_earned.get(comp, 0) / competency_points[comp] * 100, 1)
        result = {"result_id": str(uuid.uuid4()), "exam_id": exam["exam_id"], "user_id": exam["user_id"], "track": exam["track"], "track_name": exam["track_name"], "exam_date": datetime.now().isoformat(), "score": score_pct, "max_score": 100.0, "earned_points": earned_points, "total_points": total_points, "passed": passed, "passing_score": exam["passing_score"], "time_taken_minutes": time_taken_minutes, "question_results": question_results, "competency_scores": competency_scores}
        if passed:
            config = TRACK_CONFIG[CertTrack(exam["track"])]
            result["certification_id"] = "CERT-" + hashlib.sha256(result["result_id"].encode()).hexdigest()[:12].upper()
            result["expires_at"] = (datetime.now() + timedelta(days=30 * config["validity_months"])).isoformat()
        self.results[result["result_id"]] = result
        self._save_results()
        return result

    def get_certification_status(self, user_id):
        user_results = [r for r in self.results.values() if r["user_id"] == user_id]
        active_certs = []
        expired_certs = []
        now = datetime.now()
        for r in user_results:
            if r.get("certification_id"):
                expires = datetime.fromisoformat(r["expires_at"])
                cert_info = {"certification_id": r["certification_id"], "track": r["track"], "track_name": r["track_name"], "earned_date": r["exam_date"], "expires_at": r["expires_at"], "score": r["score"]}
                if expires > now:
                    active_certs.append(cert_info)
                else:
                    expired_certs.append(cert_info)
        return {"user_id": user_id, "active_certifications": active_certs, "expired_certifications": expired_certs, "total_exams_taken": len(user_results), "total_passed": sum(1 for r in user_results if r["passed"]), "average_score": round(sum(r["score"] for r in user_results) / len(user_results), 1) if user_results else 0}


def main():
    import argparse
    parser = argparse.ArgumentParser(description="GRC_Claw Certification Exam Generator")
    parser.add_argument("--track", type=str, choices=[t.value for t in CertTrack])
    parser.add_argument("--user", type=str, default="anonymous")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--list-tracks", action="store_true")
    parser.add_argument("--status", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    gen = ExamGenerator()
    if args.list_tracks:
        tracks = [{"track": t.value, "name": c["name"], "description": c["description"], "questions": c["num_questions"], "passing_score": c["passing_score"], "time_limit": c["time_limit_minutes"]} for t, c in TRACK_CONFIG.items()]
        if args.json:
            print(json.dumps(tracks, indent=2))
        else:
            print("\n{:<25} {:<25} {:<12} {:<10} {:<10}".format("Track", "Name", "Questions", "Passing", "Time"))
            print("-" * 90)
            for t in tracks:
                print("{:<25} {:<25} {:<12} {:<10} {} min".format(t["track"], t["name"], t["questions"], t["passing_score"], t["time_limit"]))
    elif args.generate and args.track:
        exam = gen.generate_exam(CertTrack(args.track), args.user)
        if args.json:
            print(json.dumps(exam, indent=2))
        else:
            print("\n" + "=" * 60)
            print("Certification Exam: {}".format(exam["track_name"]))
            print("=" * 60)
            print("Exam ID: {}".format(exam["exam_id"]))
            print("Questions: {}".format(exam["total_questions"]))
            print("Total Points: {}".format(exam["total_points"]))
            print("Time Limit: {} minutes".format(exam["time_limit_minutes"]))
            print("Passing Score: {}%".format(exam["passing_score"]))
            print("\n--- Questions ---")
            for q in exam["questions"]:
                print("\n[{}] ({}, {} pts) {}".format(q["question_id"], q["difficulty"], q["points"], q["question_text"]))
                if q.get("scenario"):
                    print("  Scenario: {}".format(q["scenario"]))
                for i, opt in enumerate(q["options"]):
                    print("  {}. {}".format(chr(65 + i), opt))
    elif args.status:
        status = gen.get_certification_status(args.user)
        if args.json:
            print(json.dumps(status, indent=2))
        else:
            print("\n" + "=" * 60)
            print("Certification Status for {}".format(args.user))
            print("=" * 60)
            print("Total Exams: {}".format(status["total_exams_taken"]))
            print("Passed: {}".format(status["total_passed"]))
            print("Average Score: {}%".format(status["average_score"]))
            if status["active_certifications"]:
                print("\n--- Active Certifications ---")
                for c in status["active_certifications"]:
                    print("  {} | {} | Score: {}% | Expires: {}".format(c["certification_id"], c["track_name"], c["score"], c["expires_at"][:10]))
            if status["expired_certifications"]:
                print("\n--- Expired Certifications ---")
                for c in status["expired_certifications"]:
                    print("  {} | {} | Expired: {}".format(c["certification_id"], c["track_name"], c["expires_at"][:10]))
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
