apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-taints-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-taints: "dedicated=event-management:NoSchedule"

target:
  kind: Deployment
  name: event-management
