apiVersion: builtin
kind: ImageTransformer
metadata:
  name: image-config
image:
  name: grcclaw/event-management
  newTag: stable
fieldSpecs:
  - path: spec/template/spec/containers/image
    create: true
