#!/usr/bin/env bash
# Setup script for the model routing system.
# Installs dependencies, validates configuration, and initializes the routing environment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROUTING_DIR="$(dirname "$SCRIPT_DIR")"
VENV_DIR="${ROUTING_DIR}/.venv"
CONFIG_DIR="${ROUTING_DIR}/config"
LOG_DIR="${ROUTING_DIR}/logs"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check Python version
check_python() {
    log_info "Checking Python installation..."

    if ! command -v python3 &> /dev/null; then
        log_error "Python 3 is not installed. Please install Python 3.9+."
        exit 1
    fi

    PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
    REQUIRED_VERSION="3.9"

    if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
        log_error "Python $PYTHON_VERSION is not supported. Python $REQUIRED_VERSION+ required."
        exit 1
    fi

    log_success "Python $PYTHON_VERSION found"
}

# Create virtual environment
setup_venv() {
    log_info "Setting up virtual environment..."

    if [ -d "$VENV_DIR" ]; then
        log_warn "Virtual environment already exists at $VENV_DIR"
    else
        python3 -m venv "$VENV_DIR"
        log_success "Created virtual environment at $VENV_DIR"
    fi

    # shellcheck source=/dev/null
    source "$VENV_DIR/bin/activate"

    pip install --upgrade pip setuptools wheel > /dev/null 2>&1
    log_success "Upgraded pip"
}

# Install dependencies
install_deps() {
    log_info "Installing dependencies..."

    # Core dependencies (stdlib-only, but include optional ones)
    pip install typing-extensions > /dev/null 2>&1 || true

    # Optional: Install development dependencies
    if [ "${INSTALL_DEV:-0}" = "1" ]; then
        log_info "Installing development dependencies..."
        pip install pytest pytest-cov mypy ruff > /dev/null 2>&1 || {
            log_warn "Some development dependencies failed to install"
        }
    fi

    log_success "Dependencies installed"
}

# Create directory structure
create_dirs() {
    log_info "Creating directory structure..."

    mkdir -p "$CONFIG_DIR"
    mkdir -p "$LOG_DIR"

    log_success "Directories created"
}

# Create default configuration
create_config() {
    log_info "Creating default configuration..."

    CONFIG_FILE="${CONFIG_DIR}/routing.yaml"

    if [ -f "$CONFIG_FILE" ]; then
        log_warn "Configuration file already exists at $CONFIG_FILE"
    else
        cat > "$CONFIG_FILE" << 'EOF'
# Model Routing Configuration
# Generated by setup-routing.sh

routing:
  default_tier: "balanced"
  complexity_thresholds:
    ultra_fast: 0.2
    fast: 0.4
    balanced: 0.6
    quality: 0.8
    ultra_quality: 1.0

models:
  - name: "gpt-4o-mini"
    tier: "fast"
    max_tokens: 128000
    cost_per_1k_tokens: 0.00015
    avg_latency_ms: 150
    quality_score: 0.75
    capabilities: ["text", "function_calling"]
    supports_streaming: true
    supports_vision: false
    supports_function_calling: true

  - name: "gpt-4o"
    tier: "quality"
    max_tokens: 128000
    cost_per_1k_tokens: 0.0025
    avg_latency_ms: 800
    quality_score: 0.90
    capabilities: ["text", "vision", "function_calling"]
    supports_streaming: true
    supports_vision: true
    supports_function_calling: true

  - name: "claude-3-haiku"
    tier: "ultra_fast"
    max_tokens: 200000
    cost_per_1k_tokens: 0.00025
    avg_latency_ms: 80
    quality_score: 0.70
    capabilities: ["text"]
    supports_streaming: true
    supports_vision: false
    supports_function_calling: false

budget:
  daily:
    max_tokens: 1000000
    max_cost_usd: 50.0
    hard_limit: true
  monthly:
    max_tokens: 20000000
    max_cost_usd: 500.0
    hard_limit: true

cache:
  enabled: true
  similarity_threshold: 0.85
  max_entries: 10000
  default_ttl_seconds: 3600

fallback:
  max_retries: 2
  exponential_backoff: true
  circuit_breaker_threshold: 5
  circuit_breaker_timeout_seconds: 60

latency:
  target_p95_ms: 1000
  max_acceptable_ms: 5000
  enable_prefetching: true
  enable_parallel: true

laya:
  enabled: false
  base_url: "https://api.laya.ai/v1"
  timeout_seconds: 30
  max_retries: 3
EOF
        log_success "Created configuration at $CONFIG_FILE"
    fi
}

# Validate installation
validate() {
    log_info "Validating installation..."

    # shellcheck source=/dev/null
    source "$VENV_DIR/bin/activate"

    python3 -c "
import sys
sys.path.insert(0, '${ROUTING_DIR}')
try:
    from routing import ModelRouter, LayaClient, TokenBudget, CostMonitor
    from routing import SemanticCache, FallbackChain, QualityScorer, LatencyOptimizer
    print('All modules imported successfully')
except ImportError as e:
    print(f'Import error: {e}')
    sys.exit(1)
" || {
        log_error "Validation failed"
        exit 1
    }

    log_success "Validation passed"
}

# Print usage information
print_usage() {
    echo ""
    echo "Model Routing System - Setup Complete"
    echo "====================================="
    echo ""
    echo "To activate the environment:"
    echo "  source ${VENV_DIR}/bin/activate"
    echo ""
    echo "To use the routing system:"
    echo "  python3 -c \"from routing import ModelRouter; ...\""
    echo ""
    echo "Configuration file: ${CONFIG_FILE}"
    echo "Log directory: ${LOG_DIR}"
    echo ""
    echo "Environment variables:"
    echo "  INSTALL_DEV=1  - Install development dependencies"
    echo ""
}

# Main setup
main() {
    echo "Model Routing System Setup"
    echo "=========================="
    echo ""

    check_python
    setup_venv
    install_deps
    create_dirs
    create_config
    validate
    print_usage

    log_success "Setup complete!"
}

main "$@"
