apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-services-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-optimizer
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-services: "seo-optimizer-*"

target:
  kind: Deployment
  name: seo-optimizer
