apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: image-tag-config
imageTag:
  name: grcclaw/seo-optimizer
  newTag: stable
fieldSpecs:
  - path: spec/template/spec/containers/image
    create: true
