apiVersion: builtin
kind: PatchTransformer
metadata:
  name: nebula-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-optimizer
spec:
  template:
    metadata:
      annotations:
        nebula.io/enable: "true"

target:
  kind: Deployment
  name: seo-optimizer
