apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sonarqube-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-optimizer
spec:
  template:
    metadata:
      annotations:
        sonarqube.org/project-key: seo-optimizer

target:
  kind: Deployment
  name: seo-optimizer
