apiVersion: builtin
kind: PatchTransformer
metadata:
  name: checkov-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-automation
spec:
  template:
    metadata:
      annotations:
        checkov.io/skip: "false"

target:
  kind: Deployment
  name: workflow-automation
