apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-recommendations-dev

resources:
  - ../../base

patches:
  - path: ../../patches/replicas-patch.yaml
    target:
      kind: Deployment
      name: product-recommendations
  - path: ../../patches/resources-patch.yaml
    target:
      kind: Deployment
      name: product-recommendations

configMapGenerator:
  - name: product-recommendations-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - DEBUG=true

commonLabels:
  environment: development

images:
  - name: grcclaw/product-recommendations
    newTag: dev
