export type SaaSCategory =
  | "identity"
  | "devops"
  | "crm"
  | "communication"
  | "security"
  | "data"
  | "hr"
  | "finance"
  | "cloud"
  | "monitoring"
  | "other";

export type SaaSAuthType = "oauth2" | "api_key" | "bearer";

export interface SaaSCatalogEntry {
  id: string;
  name: string;
  category: SaaSCategory;
  authType: SaaSAuthType;
  apiEndpoint: string;
  capabilities: string[];
  frameworks: string[];
}

export const SAAS_CATALOG: SaaSCatalogEntry[] = [
  // ──────────────────────────────────────────────
  // Identity (6)
  // ──────────────────────────────────────────────
  {
    id: "okta",
    name: "Okta",
    category: "identity",
    authType: "api_key",
    apiEndpoint: "https://{domain}/api/v1",
    capabilities: [
      "user_lifecycle",
      "mfa_enrollment",
      "sso_audit",
      "password_policy",
      "session_management",
      "group_management",
      "application_assignment",
      "factor_verify",
      "system_log",
      "risk_event",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "CIS", "HIPAA", "PCI DSS"],
  },
  {
    id: "azure_ad",
    name: "Azure Active Directory",
    category: "identity",
    authType: "oauth2",
    apiEndpoint: "https://graph.microsoft.com/v1.0",
    capabilities: [
      "user_inventory",
      "mfa_status",
      "conditional_access",
      "risk_user",
      "app_registration",
      "service_principal",
      "group_membership",
      "role_assignment",
      "sign_in_log",
      "audit_log",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "CIS Azure", "HIPAA"],
  },
  {
    id: "google_workspace",
    name: "Google Workspace",
    category: "identity",
    authType: "oauth2",
    apiEndpoint: "https://admin.googleapis.com/admin/directory/v1",
    capabilities: [
      "user_admin",
      "mfa_enrollment",
      "saml_sso",
      "oauth_token_audit",
      "admin_audit",
      "login_activity",
      "organizational_unit",
      "group_management",
      "data_export",
      "security_setting",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "CIS Google", "HIPAA"],
  },
  {
    id: "onelogin",
    name: "OneLogin",
    category: "identity",
    authType: "api_key",
    apiEndpoint: "https://{subdomain}.onelogin.com/api/2",
    capabilities: [
      "user_management",
      "mfa_config",
      "sso_audit",
      "app_assignment",
      "password_policy",
      "risk_score",
      "auth_factor",
      "directory_sync",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "CIS", "HIPAA"],
  },
  {
    id: "ping_identity",
    name: "Ping Identity",
    category: "identity",
    authType: "oauth2",
    apiEndpoint: "https://api.pingone.com/v1",
    capabilities: [
      "user_authentication",
      "mfa_policy",
      "sso_config",
      "risk_adaptive",
      "token_management",
      "directory_sync",
      "saml_config",
      "oidc_config",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "HIPAA"],
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "identity",
    authType: "bearer",
    apiEndpoint: "https://{tenant}.auth0.com/api/v2",
    capabilities: [
      "user_management",
      "mfa_enrollment",
      "sso_config",
      "anomaly_detection",
      "attack_protection",
      "log_event",
      "tenant_setting",
      "client_application",
      "action_execution",
      "branding_config",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "HIPAA", "PCI DSS"],
  },

  // ──────────────────────────────────────────────
  // DevOps (6)
  // ──────────────────────────────────────────────
  {
    id: "github",
    name: "GitHub",
    category: "devops",
    authType: "bearer",
    apiEndpoint: "https://api.github.com",
    capabilities: [
      "repository_management",
      "branch_protection",
      "pull_request_audit",
      "code_review",
      "secret_scanning",
      "dependabot_alert",
      "code_scanning",
      "actions_workflow",
      "copilot_usage",
      "org_member",
      "deploy_key",
      "protected_branch",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF", "SLSA", "OWASP"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "devops",
    authType: "bearer",
    apiEndpoint: "https://gitlab.com/api/v4",
    capabilities: [
      "project_management",
      "merge_request_audit",
      "pipeline_execution",
      "container_registry",
      "secret_detection",
      "dependency_scanning",
      "sast_dast",
      "code_owners",
      "push_rules",
      "audit_event",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF", "SLSA"],
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "devops",
    authType: "bearer",
    apiEndpoint: "https://api.bitbucket.org/2.0",
    capabilities: [
      "repository_management",
      "branch_permission",
      "pipeline_config",
      "code_insight",
      "security_scan",
      "pull_request_approval",
      "workspace_member",
      "webhook_config",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF"],
  },
  {
    id: "jenkins",
    name: "Jenkins",
    category: "devops",
    authType: "api_key",
    apiEndpoint: "https://{host}/api/json",
    capabilities: [
      "job_configuration",
      "build_history",
      "credential_management",
      "plugin_audit",
      "user_permission",
      "queue_status",
      "node_management",
      "script_console",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF"],
  },
  {
    id: "circleci",
    name: "CircleCI",
    category: "devops",
    authType: "bearer",
    apiEndpoint: "https://circleci.com/api/v2",
    capabilities: [
      "pipeline_execution",
      "workflow_status",
      "environment_variable",
      "orb_usage",
      "context_management",
      "insights_metrics",
      "checkout_key",
      "organization_audit",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF"],
  },
  {
    id: "travisci",
    name: "Travis CI",
    category: "devops",
    authType: "bearer",
    apiEndpoint: "https://api.travis-ci.com",
    capabilities: [
      "build_status",
      "repository_config",
      "environment_variable",
      "build_history",
      "user_permission",
      "enterprise_settings",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF"],
  },

  // ──────────────────────────────────────────────
  // CRM (3)
  // ──────────────────────────────────────────────
  {
    id: "salesforce",
    name: "Salesforce",
    category: "crm",
    authType: "oauth2",
    apiEndpoint: "https://{instance}.salesforce.com/services/data/v{version}",
    capabilities: [
      "object_permission",
      "field_level_security",
      "record_access",
      "sharing_rule",
      "login_event",
      "setup_audit",
      "field_audit",
      "permission_change",
      "connected_app",
      "login_ip_range",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA"],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "crm",
    authType: "bearer",
    apiEndpoint: "https://api.hubapi.com",
    capabilities: [
      "contact_management",
      "deal_pipeline",
      "email_tracking",
      "form_submission",
      "user_permission",
      "integration_audit",
      "workflow_automation",
      "portal_setting",
    ],
    frameworks: ["SOC 2", "ISO 27001", "GDPR"],
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    category: "crm",
    authType: "bearer",
    apiEndpoint: "https://api.pipedrive.com/v1",
    capabilities: [
      "deal_management",
      "activity_tracking",
      "lead_management",
      "user_permission",
      "note_audit",
      "file_attachment",
      "pipeline_config",
    ],
    frameworks: ["SOC 2", "ISO 27001", "GDPR"],
  },

  // ──────────────────────────────────────────────
  // Communication (3)
  // ──────────────────────────────────────────────
  {
    id: "slack",
    name: "Slack",
    category: "communication",
    authType: "bearer",
    apiEndpoint: "https://slack.com/api",
    capabilities: [
      "channel_management",
      "message_history",
      "file_sharing",
      "app_installation",
      "user_identity",
      "audit_log",
      "enterprise_grid",
      "dlp_config",
      "session_setting",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "microsoft_teams",
    name: "Microsoft Teams",
    category: "communication",
    authType: "oauth2",
    apiEndpoint: "https://graph.microsoft.com/v1.0",
    capabilities: [
      "team_management",
      "channel_config",
      "message_audit",
      "meeting_policy",
      "app_permission",
      "guest_access",
      "compliance_recording",
      "data_loss_prevention",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA"],
  },
  {
    id: "discord",
    name: "Discord",
    category: "communication",
    authType: "bearer",
    apiEndpoint: "https://discord.com/api/v10",
    capabilities: [
      "server_management",
      "channel_config",
      "role_permission",
      "audit_log",
      "webhook_config",
      "member_management",
      "message_search",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },

  // ──────────────────────────────────────────────
  // Security (10)
  // ──────────────────────────────────────────────
  {
    id: "crowdstrike",
    name: "CrowdStrike Falcon",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://api.crowdstrike.com",
    capabilities: [
      "endpoint_detection",
      "threat_intelligence",
      "vulnerability_assessment",
      "device_inventory",
      "incident_detection",
      "identity_threat",
      "cloud_security",
      "usb_device_control",
      "firewall_management",
      "sensor_update_policy",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "MITRE ATT&CK", "CIS"],
  },
  {
    id: "sentinelone",
    name: "SentinelOne",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://usea1.sentinelone.net/api",
    capabilities: [
      "edr_alert",
      "threat_hunting",
      "vulnerability_management",
      "device_control",
      "firewall_management",
      "identity_threat",
      "cloud_workload",
      "storyline_analysis",
      "remote_shell",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "MITRE ATT&CK"],
  },
  {
    id: "carbon_black",
    name: "Carbon Black Cloud",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://defense.conferdeploy.com/appservices/v1/orgs/{orgId}",
    capabilities: [
      "edr_alert",
      "vulnerability_assessment",
      "audit_log",
      "device_inventory",
      "watchlist",
      "report_export",
      "policy_config",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "MITRE ATT&CK"],
  },
  {
    id: "qualys",
    name: "Qualys",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://qualysguard.{platform}.com/api/2.0/fo",
    capabilities: [
      "vulnerability_scan",
      "asset_inventory",
      "compliance_check",
      "policy_compliance",
      "web_app_scan",
      "cloud_security",
      "certificate_inventory",
      "patch_detection",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "PCI DSS", "HIPAA"],
  },
  {
    id: "nessus",
    name: "Nessus",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://{host}/rest",
    capabilities: [
      "vulnerability_scan",
      "compliance_audit",
      "policy_management",
      "scan_result",
      "plugin_feed",
      "asset_discovery",
      "credential_scan",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "PCI DSS", "CIS"],
  },
  {
    id: "rapid7",
    name: "Rapid7 InsightVM",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://insightvm.{region}.rapid7.com/api/3",
    capabilities: [
      "vulnerability_scan",
      "asset_inventory",
      "remediation_project",
      "compliance_policy",
      "site_management",
      "scan_config",
      "report_builder",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "PCI DSS"],
  },
  {
    id: "tenable",
    name: "Tenable.io",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://cloud.tenable.com",
    capabilities: [
      "vulnerability_management",
      "asset_discovery",
      "compliance_assessment",
      "web_app_scan",
      "cloud_scanning",
      "container_security",
      "identity_assessment",
      "attack_surface",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "PCI DSS", "HIPAA"],
  },
  {
    id: "snyk",
    name: "Snyk",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://api.snyk.io/v1",
    capabilities: [
      "open_source_vulnerability",
      "container_vulnerability",
      "iac_scan",
      "sast_scan",
      "license_compliance",
      "dependency_management",
      "fix_pull_request",
      "organization_audit",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF", "OWASP", "SLSA"],
  },
  {
    id: "sonarqube",
    name: "SonarQube",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://{host}/api",
    capabilities: [
      "code_quality",
      "security_hotspot",
      "vulnerability_scan",
      "code_coverage",
      "duplications",
      "quality_gate",
      "project_analysis",
      "security_rating",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF", "OWASP"],
  },
  {
    id: "checkmarx",
    name: "Checkmarx One",
    category: "security",
    authType: "bearer",
    apiEndpoint: "https://app.checkmarx.net/api",
    capabilities: [
      "sast_scan",
      "sca_scan",
      "dast_scan",
      "iac_scan",
      "api_security",
      "container_scan",
      "supply_chain",
      "cx_flow",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF", "OWASP", "PCI DSS"],
  },

  // ──────────────────────────────────────────────
  // Data (5)
  // ──────────────────────────────────────────────
  {
    id: "snowflake",
    name: "Snowflake",
    category: "data",
    authType: "oauth2",
    apiEndpoint: "https://{account}.snowflakecomputing.com/api/v2",
    capabilities: [
      "query_history",
      "data_access",
      "user_inventory",
      "role_assignment",
      "session_policy",
      "password_policy",
      "mfa_status",
      "copy_history",
      "data_transfer",
      "storage_usage",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA", "PCI DSS"],
  },
  {
    id: "databricks",
    name: "Databricks",
    category: "data",
    authType: "bearer",
    apiEndpoint: "https://{host}/api/2.0",
    capabilities: [
      "workspace_audit",
      "cluster_management",
      "notebook_access",
      "job_execution",
      "secret_scope",
      "token_management",
      "unity_catalog",
      "access_control",
      "experiment_tracking",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA", "PCI DSS"],
  },
  {
    id: "bigquery",
    name: "Google BigQuery",
    category: "data",
    authType: "oauth2",
    apiEndpoint: "https://bigquery.googleapis.com/bigquery/v2",
    capabilities: [
      "dataset_inventory",
      "table_access",
      "job_history",
      "authorized_dataset",
      "row_level_security",
      "data_masking",
      "audit_log",
      "reservation_usage",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA", "PCI DSS"],
  },
  {
    id: "redshift",
    name: "Amazon Redshift",
    category: "data",
    authType: "oauth2",
    apiEndpoint: "https://redshift.{region}.amazonaws.com",
    capabilities: [
      "cluster_inventory",
      "query_history",
      "user_access",
      "snapshot_config",
      "encryption_status",
      "vpc_config",
      "parameter_group",
      "audit_log",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA", "PCI DSS"],
  },
  {
    id: "postgresql_cloud",
    name: "PostgreSQL (Cloud Managed)",
    category: "data",
    authType: "api_key",
    apiEndpoint: "https://{host}/v1",
    capabilities: [
      "database_inventory",
      "user_management",
      "role_assignment",
      "connection_log",
      "query_audit",
      "backup_config",
      "ssl_config",
      "pitr_status",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA", "PCI DSS"],
  },

  // ──────────────────────────────────────────────
  // HR (4)
  // ──────────────────────────────────────────────
  {
    id: "workday",
    name: "Workday",
    category: "hr",
    authType: "bearer",
    apiEndpoint: "https://{tenant}.myworkday.com/wday/api/{tenant}/hcm",
    capabilities: [
      "employee_management",
      "role_assignment",
      "access_review",
      "separation_process",
      "compensation_change",
      "training_completion",
      "policy_acknowledgment",
      "audit_event",
    ],
    frameworks: ["SOC 2", "ISO 27001", "SOX"],
  },
  {
    id: "bamboohr",
    name: "BambooHR",
    category: "hr",
    authType: "bearer",
    apiEndpoint: "https://api.bamboohr.com/api/gateway.php/{companyDomain}/v1",
    capabilities: [
      "employee_directory",
      "time_off_management",
      "onboarding_checklist",
      "performance_review",
      "company_policy",
      "training_log",
      "benefits_enrollment",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "gusto",
    name: "Gusto",
    category: "hr",
    authType: "bearer",
    apiEndpoint: "https://api.gusto.com/v1",
    capabilities: [
      "employee_management",
      "payroll_processing",
      "benefits_admin",
      "onboarding",
      "time_off_request",
      "document_upload",
      "contractor_management",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "rippling",
    name: "Rippling",
    category: "hr",
    authType: "bearer",
    apiEndpoint: "https://api.rippling.com/platform/1",
    capabilities: [
      "employee_management",
      "it_provisioning",
      "device_management",
      "app_access",
      "payroll",
      "benefits",
      "training_completion",
      "org_chart",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA"],
  },

  // ──────────────────────────────────────────────
  // Finance (3)
  // ──────────────────────────────────────────────
  {
    id: "quickbooks",
    name: "QuickBooks Online",
    category: "finance",
    authType: "oauth2",
    apiEndpoint: "https://quickbooks.api.intuit.com/v3/company/{companyId}",
    capabilities: [
      "invoice_management",
      "expense_tracking",
      "chart_of_accounts",
      "financial_report",
      "user_permission",
      "audit_log",
      "tax_compliance",
      "budget_tracking",
    ],
    frameworks: ["SOC 2", "ISO 27001", "SOX"],
  },
  {
    id: "netsuite",
    name: "Oracle NetSuite",
    category: "finance",
    authType: "bearer",
    apiEndpoint: "https://{account}.suitetalk.api.netsuite.com/services/rest/record/v1",
    capabilities: [
      "financial_management",
      "revenue_recognition",
      "procurement",
      "expense_management",
      "audit_log",
      "role_permission",
      "saved_search",
      "workflow_automation",
    ],
    frameworks: ["SOC 2", "ISO 27001", "SOX", "PCI DSS"],
  },
  {
    id: "xero",
    name: "Xero",
    category: "finance",
    authType: "oauth2",
    apiEndpoint: "https://api.xero.com/api.xro/2.0",
    capabilities: [
      "account_management",
      "invoice_processing",
      "bank_reconciliation",
      "payroll_management",
      "financial_report",
      "user_permission",
      "audit_trail",
      "fixed_asset",
    ],
    frameworks: ["SOC 2", "ISO 27001", "GDPR"],
  },

  // ──────────────────────────────────────────────
  // Cloud (6)
  // ──────────────────────────────────────────────
  {
    id: "aws",
    name: "Amazon Web Services",
    category: "cloud",
    authType: "oauth2",
    apiEndpoint: "https://{service}.{region}.amazonaws.com",
    capabilities: [
      "iam_audit",
      "cloudtrail_log",
      "security_hub",
      "guardduty_finding",
      "config_compliance",
      "s3_audit",
      "ec2_inventory",
      "rds_config",
      "kms_key_audit",
      "vpc_flow_log",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "CIS AWS", "HIPAA", "PCI DSS"],
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    category: "cloud",
    authType: "oauth2",
    apiEndpoint: "https://management.azure.com",
    capabilities: [
      "defender_for_cloud",
      "sentinel_alert",
      "ad_audit",
      "policy_compliance",
      "key_vault_audit",
      "nsg_flow_log",
      "storage_audit",
      "sql_audit",
      "activity_log",
      "resource_compliance",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "CIS Azure", "HIPAA", "PCI DSS"],
  },
  {
    id: "gcp",
    name: "Google Cloud Platform",
    category: "cloud",
    authType: "oauth2",
    apiEndpoint: "https://cloud.googleapis.com",
    capabilities: [
      "security_command_center",
      "cloud_logging",
      "iam_audit",
      "vpc_flow_log",
      "kms_audit",
      "compute_inventory",
      "gke_config",
      "cloud_sql_audit",
      "cloud_armor",
      "dlp_inspection",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "CIS GCP", "HIPAA", "PCI DSS"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cloud",
    authType: "bearer",
    apiEndpoint: "https://api.cloudflare.com/client/v4",
    capabilities: [
      "waf_rule",
      "access_application",
      "gateway_policy",
      "dns_analytics",
      "ssl_config",
      "r2_storage",
      "zero_trust",
      "browser_isolation",
      "dlp_config",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "PCI DSS", "OWASP"],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "cloud",
    authType: "bearer",
    apiEndpoint: "https://api.vercel.com/v9",
    capabilities: [
      "project_deployment",
      "environment_variable",
      "domain_config",
      "firewall_rule",
      "analytics",
      "log_drain",
      "team_member",
      "integration_audit",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "cloud",
    authType: "bearer",
    apiEndpoint: "https://api.netlify.com/api/v1",
    capabilities: [
      "site_deployment",
      "form_submission",
      "identity_config",
      "dns_config",
      "ssl_config",
      "environment_variable",
      "team_member",
      "log_drain",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },

  // ──────────────────────────────────────────────
  // Monitoring (5)
  // ──────────────────────────────────────────────
  {
    id: "datadog",
    name: "Datadog",
    category: "monitoring",
    authType: "api_key",
    apiEndpoint: "https://api.datadoghq.com/api/v2",
    capabilities: [
      "metric_query",
      "log_management",
      "apm_trace",
      "security_signal",
      "monitor_alert",
      "dashboard_config",
      "cspm_finding",
      "ci_visibility",
      "host_inventory",
      "sensitive_data_scan",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "MITRE ATT&CK"],
  },
  {
    id: "new_relic",
    name: "New Relic",
    category: "monitoring",
    authType: "bearer",
    apiEndpoint: "https://api.newrelic.com/v2",
    capabilities: [
      "apm_metric",
      "infrastructure_metric",
      "log_management",
      "browser_monitoring",
      "synthetic_monitoring",
      "alert_condition",
      "nrql_query",
      "entity_management",
      "service_level",
      "vulnerability_management",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    category: "monitoring",
    authType: "bearer",
    apiEndpoint: "https://api.pagerduty.com",
    capabilities: [
      "incident_management",
      "escalation_policy",
      "on_call_schedule",
      "service_catalog",
      "post_mortem",
      "automation_action",
      "event_orchestration",
      "user_permission",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
  },
  {
    id: "opsgenie",
    name: "Atlassian Opsgenie",
    category: "monitoring",
    authType: "bearer",
    apiEndpoint: "https://api.atlassian.com/opsgenie/api/v2",
    capabilities: [
      "alert_management",
      "incident_tracking",
      "escalation_policy",
      "on_call_schedule",
      "notification_rule",
      "service_heartbeat",
      "integration_config",
      "post_mortem",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF"],
  },
  {
    id: "splunk_siem",
    name: "Splunk Enterprise Security",
    category: "monitoring",
    authType: "bearer",
    apiEndpoint: "https://{host}/servicesNS/-/-/search/jobs/export",
    capabilities: [
      "notable_event",
      "risk_score",
      "correlation_search",
      "threat_intelligence",
      "audit_log",
      "saved_search",
      "lookup_table",
      "asset_identity",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST CSF", "MITRE ATT&CK"],
  },

  // ──────────────────────────────────────────────
  // Other (8)
  // ──────────────────────────────────────────────
  {
    id: "jira",
    name: "Jira Software",
    category: "other",
    authType: "bearer",
    apiEndpoint: "https://{domain}.atlassian.net/rest/api/3",
    capabilities: [
      "issue_tracking",
      "sprint_management",
      "workflow_transition",
      "field_audit",
      "permission_scheme",
      "board_config",
      "release_management",
      "component_inventory",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "asana",
    name: "Asana",
    category: "other",
    authType: "bearer",
    apiEndpoint: "https://app.asana.com/api/1.0",
    capabilities: [
      "project_management",
      "task_tracking",
      "team_membership",
      "workspace_audit",
      "custom_field",
      "portfolio_view",
      "goal_tracking",
    ],
    frameworks: ["SOC 2", "ISO 27001", "GDPR"],
  },
  {
    id: "monday",
    name: "Monday.com",
    category: "other",
    authType: "bearer",
    apiEndpoint: "https://{account}.monday.com/v2",
    capabilities: [
      "board_management",
      "item_tracking",
      "workflow_automation",
      "integration_audit",
      "team_permission",
      "document_version",
      "dashboard_config",
    ],
    frameworks: ["SOC 2", "ISO 27001", "GDPR"],
  },
  {
    id: "notion",
    name: "Notion",
    category: "other",
    authType: "bearer",
    apiEndpoint: "https://api.notion.com/v1",
    capabilities: [
      "page_management",
      "database_query",
      "workspace_audit",
      "member_permission",
      "integration_token",
      "template_library",
      "page_history",
    ],
    frameworks: ["SOC 2", "ISO 27001", "GDPR"],
  },
  {
    id: "confluence",
    name: "Atlassian Confluence",
    category: "other",
    authType: "bearer",
    apiEndpoint: "https://{domain}.atlassian.net/wiki/rest/api",
    capabilities: [
      "page_management",
      "space_permission",
      "attachment_audit",
      "content_history",
      "user_permission",
      "analytics_view",
      "template_library",
    ],
    frameworks: ["SOC 2", "ISO 27001"],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "other",
    authType: "bearer",
    apiEndpoint: "https://api.dropboxapi.com/2",
    capabilities: [
      "file_management",
      "sharing_permission",
      "version_history",
      "link_sharing",
      "admin_audit",
      "device_management",
      "storage_usage",
      "paper_audit",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA"],
  },
  {
    id: "box",
    name: "Box",
    category: "other",
    authType: "bearer",
    apiEndpoint: "https://api.box.com/2.0",
    capabilities: [
      "file_management",
      "collaboration_permission",
      "classification_label",
      "retention_policy",
      "metadata_template",
      "admin_audit",
      "user_permission",
      "enterprise_events",
    ],
    frameworks: ["SOC 2", "ISO 27001", "HIPAA", "FedRAMP"],
  },
  {
    id: "gitlab_projects",
    name: "GitLab Projects",
    category: "devops",
    authType: "bearer",
    apiEndpoint: "https://gitlab.com/api/v4/projects",
    capabilities: [
      "project_config",
      "protected_branch",
      "merge_request",
      "pipeline_status",
      "container_registry",
      "dependency_scanning",
    ],
    frameworks: ["SOC 2", "ISO 27001", "NIST SSDF"],
  },
];

// ─── Lookup Helpers ──────────────────────────────────────────────

export function getSAASEntryById(id: string): SaaSCatalogEntry | undefined {
  return SAAS_CATALOG.find((e) => e.id === id);
}

export function getSAASEntriesByCategory(category: SaaSCategory): SaaSCatalogEntry[] {
  return SAAS_CATALOG.filter((e) => e.category === category);
}

export function getSAASEntriesByFramework(framework: string): SaaSCatalogEntry[] {
  return SAAS_CATALOG.filter((e) => e.frameworks.includes(framework));
}

export function getSAASCategories(): SaaSCategory[] {
  return [...new Set(SAAS_CATALOG.map((e) => e.category))];
}

export function getSAASCatalogSummary(): Record<SaaSCategory, number> {
  const summary: Partial<Record<SaaSCategory, number>> = {};
  for (const entry of SAAS_CATALOG) {
    summary[entry.category] = (summary[entry.category] || 0) + 1;
  }
  return summary as Record<SaaSCategory, number>;
}
