apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-domains-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-domains: "example.com"

target:
  kind: Deployment
  name: smb-marketing
