apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-mig-fan-mode-performance-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-mig-fan-mode-performance: "false"

target:
  kind: Deployment
  name: smb-marketing
