apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-ingresses-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-ingresses: "smb-marketing-*"

target:
  kind: Deployment
  name: smb-marketing
