apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: ecommerce-marketing-restore
spec:
  backupName: ecommerce-marketing-backup
  includedNamespaces:
    - ecommerce-marketing-prod
  restorePVs: true

target:
  kind: Deployment
  name: ecommerce-marketing
