apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-node-gpu-count-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-node-gpu-count: "1"

target:
  kind: Deployment
  name: ecommerce-marketing
