apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-oidc-allowed-services-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-marketing
spec:
  template:
    metadata:
      annotations:
        headscale.io/oidc-allowed-services: "ecommerce-marketing-*"

target:
  kind: Deployment
  name: ecommerce-marketing
