apiVersion: builtin
kind: PatchTransformer
metadata:
  name: vxlan-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: vxlan-conf

target:
  kind: Deployment
  name: analytics
