apiVersion: builtin
kind: PatchTransformer
metadata:
  name: monitoring-patch
patch: |-
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: onboarding-training-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: onboarding-training
  endpoints:
    - port: http
      interval: 30s
      path: /metrics

target:
  kind: Deployment
  name: onboarding-training
