"""
Integration Monitoring — Health checks, metrics, alerting, and tracing.
"""

from __future__ import annotations

import json
import logging
import time
import uuid
from abc import ABC, abstractmethod
from collections import defaultdict
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime, timezone
from enum import Enum
from threading import Lock
from typing import Any, Optional

logger = logging.getLogger(__name__)


class HealthStatus(str, Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    UNKNOWN = "unknown"


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class HealthCheckResult:
    """Result of a health check."""

    name: str
    status: HealthStatus
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    response_time_ms: float = 0.0
    message: str = ""
    details: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class MetricPoint:
    """A single metric data point."""

    name: str
    value: float
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    labels: dict[str, str] = field(default_factory=dict)
    unit: str = ""


@dataclass
class Alert:
    """An alert generated by the monitoring system."""

    alert_id: str = field(default_factory=lambda: str(uuid.uuid4())[:12])
    name: str = ""
    severity: AlertSeverity = AlertSeverity.WARNING
    message: str = ""
    source: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    acknowledged: bool = False
    resolved: bool = False
    resolved_at: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class TraceSpan:
    """A single span in a distributed trace."""

    trace_id: str = ""
    span_id: str = field(default_factory=lambda: str(uuid.uuid4())[:16])
    parent_span_id: str | None = None
    name: str = ""
    start_time: str = ""
    end_time: str = ""
    duration_ms: float = 0.0
    status: str = "ok"
    attributes: dict[str, Any] = field(default_factory=dict)
    events: list[dict[str, Any]] = field(default_factory=list)


class HealthChecker:
    """
    Performs health checks on connectors and integrations.

    Supports:
    - Custom health check functions
    - Periodic health checks
    - Health check history
    - Status aggregation
    """

    def __init__(self):
        self._checks: dict[str, Callable] = {}
        self._history: dict[str, list[HealthCheckResult]] = defaultdict(list)
        self._max_history: int = 100
        self._lock = Lock()

    def register(self, name: str, check_func: Callable) -> None:
        """Register a health check function."""
        self._checks[name] = check_func

    def unregister(self, name: str) -> None:
        """Unregister a health check."""
        self._checks.pop(name, None)

    def check(self, name: str) -> HealthCheckResult:
        """Run a single health check."""
        check_func = self._checks.get(name)
        if not check_func:
            return HealthCheckResult(
                name=name,
                status=HealthStatus.UNKNOWN,
                message=f"No health check registered for '{name}'",
            )

        start = time.monotonic()
        try:
            result = check_func()
            elapsed_ms = (time.monotonic() - start) * 1000

            if isinstance(result, HealthCheckResult):
                result.response_time_ms = elapsed_ms
                if not result.timestamp:
                    result.timestamp = datetime.now(UTC).isoformat()
            elif isinstance(result, dict):
                result = HealthCheckResult(
                    name=name,
                    status=HealthStatus(result.get("status", "unknown")),
                    response_time_ms=elapsed_ms,
                    message=result.get("message", ""),
                    details=result.get("details", {}),
                )
            else:
                result = HealthCheckResult(
                    name=name,
                    status=HealthStatus.HEALTHY if result else HealthStatus.UNHEALTHY,
                    response_time_ms=elapsed_ms,
                )

        except Exception as e:
            elapsed_ms = (time.monotonic() - start) * 1000
            result = HealthCheckResult(
                name=name,
                status=HealthStatus.UNHEALTHY,
                response_time_ms=elapsed_ms,
                message=f"Health check failed: {e}",
                details={"error": str(e), "error_type": type(e).__name__},
            )

        with self._lock:
            self._history[name].append(result)
            if len(self._history[name]) > self._max_history:
                self._history[name] = self._history[name][-self._max_history:]

        return result

    def check_all(self) -> dict[str, HealthCheckResult]:
        """Run all registered health checks."""
        return {name: self.check(name) for name in self._checks}

    def get_history(self, name: str, limit: int = 10) -> list[HealthCheckResult]:
        """Get health check history for a specific check."""
        return self._history.get(name, [])[-limit:]

    def get_overall_status(self) -> HealthStatus:
        """Get aggregated status across all checks."""
        results = self.check_all()
        if not results:
            return HealthStatus.UNKNOWN

        statuses = [r.status for r in results.values()]
        if any(s == HealthStatus.UNHEALTHY for s in statuses):
            return HealthStatus.UNHEALTHY
        elif any(s == HealthStatus.DEGRADED for s in statuses):
            return HealthStatus.DEGRADED
        elif all(s == HealthStatus.HEALTHY for s in statuses):
            return HealthStatus.HEALTHY
        return HealthStatus.UNKNOWN


class IntegrationMetrics:
    """
    Collects and aggregates integration metrics.

    Tracks:
    - Request counts and rates
    - Error rates
    - Latency percentiles
    - Throughput
    - Connector-specific metrics
    """

    def __init__(self):
        self._counters: dict[str, int] = defaultdict(int)
        self._gauges: dict[str, float] = {}
        self._histograms: dict[str, list[float]] = defaultdict(list)
        self._timers: dict[str, list[float]] = defaultdict(list)
        self._lock = Lock()

    def increment(self, name: str, value: int = 1, labels: dict[str, str] | None = None) -> None:
        """Increment a counter metric."""
        key = self._make_key(name, labels)
        with self._lock:
            self._counters[key] += value

    def gauge(self, name: str, value: float, labels: dict[str, str] | None = None) -> None:
        """Set a gauge metric."""
        key = self._make_key(name, labels)
        with self._lock:
            self._gauges[key] = value

    def histogram(self, name: str, value: float, labels: dict[str, str] | None = None) -> None:
        """Record a histogram observation."""
        key = self._make_key(name, labels)
        with self._lock:
            self._histograms[key].append(value)
            # Keep last 10000 observations
            if len(self._histograms[key]) > 10000:
                self._histograms[key] = self._histograms[key][-10000:]

    def timer(self, name: str, value_ms: float, labels: dict[str, str] | None = None) -> None:
        """Record a timer observation."""
        key = self._make_key(name, labels)
        with self._lock:
            self._timers[key].append(value_ms)
            if len(self._timers[key]) > 10000:
                self._timers[key] = self._timers[key][-10000:]

    def get_counter(self, name: str, labels: dict[str, str] | None = None) -> int:
        """Get a counter value."""
        key = self._make_key(name, labels)
        return self._counters.get(key, 0)

    def get_gauge(self, name: str, labels: dict[str, str] | None = None) -> float:
        """Get a gauge value."""
        key = self._make_key(name, labels)
        return self._gauges.get(key, 0.0)

    def get_histogram_stats(self, name: str, labels: dict[str, str] | None = None) -> dict[str, float]:
        """Get histogram statistics (count, min, max, avg, p50, p95, p99)."""
        key = self._make_key(name, labels)
        values = sorted(self._histograms.get(key, []))
        if not values:
            return {"count": 0, "min": 0, "max": 0, "avg": 0, "p50": 0, "p95": 0, "p99": 0}

        n = len(values)
        return {
            "count": n,
            "min": values[0],
            "max": values[-1],
            "avg": sum(values) / n,
            "p50": values[int(n * 0.50)],
            "p95": values[int(n * 0.95)],
            "p99": values[int(n * 0.99)],
        }

    def get_timer_stats(self, name: str, labels: dict[str, str] | None = None) -> dict[str, float]:
        """Get timer statistics."""
        return self.get_histogram_stats(name, labels)

    def get_all_metrics(self) -> dict[str, Any]:
        """Get all metrics as a dict."""
        return {
            "counters": dict(self._counters),
            "gauges": dict(self._gauges),
            "histograms": {k: self.get_histogram_stats(k) for k in self._histograms},
            "timers": {k: self.get_timer_stats(k) for k in self._timers},
        }

    def reset(self) -> None:
        """Reset all metrics."""
        with self._lock:
            self._counters.clear()
            self._gauges.clear()
            self._histograms.clear()
            self._timers.clear()

    def _make_key(self, name: str, labels: dict[str, str] | None = None) -> str:
        if not labels:
            return name
        label_str = ",".join(f"{k}={v}" for k, v in sorted(labels.items()))
        return f"{name}{{{label_str}}}"


class AlertManager:
    """
    Manages alerts for integration monitoring.

    Supports:
    - Alert rules with thresholds
    - Alert deduplication
    - Alert routing to channels
    - Alert acknowledgment and resolution
    """

    def __init__(self):
        self._alerts: dict[str, Alert] = {}
        self._rules: list[dict[str, Any]] = []
        self._channels: list[Callable] = []
        self._dedup_window_seconds: float = 300.0  # 5 minutes
        self._recent_alerts: dict[str, str] = {}  # rule_name -> alert_id
        self._lock = Lock()

    def add_rule(
        self,
        name: str,
        condition: Callable,
        severity: AlertSeverity = AlertSeverity.WARNING,
        message: str = "",
        source: str = "",
        dedup: bool = True,
    ) -> None:
        """Add an alert rule."""
        self._rules.append({
            "name": name,
            "condition": condition,
            "severity": severity,
            "message": message,
            "source": source,
            "dedup": dedup,
        })

    def add_channel(self, channel: Callable) -> None:
        """Add an alert notification channel."""
        self._channels.append(channel)

    def evaluate(self, context: dict[str, Any] | None = None) -> list[Alert]:
        """Evaluate all alert rules and generate alerts."""
        new_alerts = []
        ctx = context or {}

        for rule in self._rules:
            try:
                triggered = rule["condition"](ctx)
                if not triggered:
                    continue

                # Deduplication
                if rule.get("dedup", True):
                    rule_name = rule["name"]
                    if rule_name in self._recent_alerts:
                        existing = self._alerts.get(self._recent_alerts[rule_name])
                        if existing and not existing.resolved:
                            continue

                alert = Alert(
                    name=rule["name"],
                    severity=rule["severity"],
                    message=rule["message"],
                    source=rule["source"],
                    metadata=ctx,
                )

                with self._lock:
                    self._alerts[alert.alert_id] = alert
                    self._recent_alerts[rule["name"]] = alert.alert_id

                new_alerts.append(alert)

                # Notify channels
                for channel in self._channels:
                    try:
                        channel(alert)
                    except Exception as e:
                        logger.error("Alert channel error: %s", e)

            except Exception as e:
                logger.error("Alert rule evaluation error: %s", e)

        return new_alerts

    def acknowledge(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        with self._lock:
            alert = self._alerts.get(alert_id)
            if alert:
                alert.acknowledged = True
                return True
        return False

    def resolve(self, alert_id: str) -> bool:
        """Resolve an alert."""
        with self._lock:
            alert = self._alerts.get(alert_id)
            if alert:
                alert.resolved = True
                alert.resolved_at = datetime.now(UTC).isoformat()
                return True
        return False

    def get_alerts(
        self,
        severity: AlertSeverity | None = None,
        acknowledged: bool | None = None,
        resolved: bool | None = None,
    ) -> list[Alert]:
        """Get alerts with optional filtering."""
        results = list(self._alerts.values())
        if severity:
            results = [a for a in results if a.severity == severity]
        if acknowledged is not None:
            results = [a for a in results if a.acknowledged == acknowledged]
        if resolved is not None:
            results = [a for a in results if a.resolved == resolved]
        return results

    def get_active_alerts(self) -> list[Alert]:
        """Get all unresolved alerts."""
        return [a for a in self._alerts.values() if not a.resolved]


class IntegrationTracer:
    """
    Distributed tracing for integration operations.

    Tracks:
    - Request flows across connectors
    - Span timing and hierarchy
    - Error tracking
    - Context propagation
    """

    def __init__(self):
        self._traces: dict[str, list[TraceSpan]] = defaultdict(list)
        self._active_spans: dict[str, TraceSpan] = {}
        self._max_traces: int = 1000
        self._lock = Lock()

    def start_span(
        self,
        name: str,
        trace_id: str = "",
        parent_span_id: str | None = None,
        attributes: dict[str, Any] | None = None,
    ) -> TraceSpan:
        """Start a new trace span."""
        span = TraceSpan(
            trace_id=trace_id or str(uuid.uuid4())[:16],
            parent_span_id=parent_span_id,
            name=name,
            start_time=datetime.now(UTC).isoformat(),
            attributes=attributes or {},
        )
        self._active_spans[span.span_id] = span
        return span

    def end_span(
        self,
        span_id: str,
        status: str = "ok",
        attributes: dict[str, Any] | None = None,
    ) -> TraceSpan | None:
        """End a trace span."""
        span = self._active_spans.pop(span_id, None)
        if not span:
            return None

        span.end_time = datetime.now(UTC).isoformat()
        span.status = status

        # Calculate duration
        try:
            start = datetime.fromisoformat(span.start_time)
            end = datetime.fromisoformat(span.end_time)
            span.duration_ms = (end - start).total_seconds() * 1000
        except (ValueError, TypeError):
            pass

        if attributes:
            span.attributes.update(attributes)

        with self._lock:
            self._traces[span.trace_id].append(span)
            # Trim old traces
            if len(self._traces) > self._max_traces:
                oldest = min(self._traces.keys())
                del self._traces[oldest]

        return span

    def add_event(self, span_id: str, name: str, attributes: dict[str, Any] | None = None) -> None:
        """Add an event to an active span."""
        span = self._active_spans.get(span_id)
        if span:
            span.events.append({
                "name": name,
                "timestamp": datetime.now(UTC).isoformat(),
                "attributes": attributes or {},
            })

    def get_trace(self, trace_id: str) -> list[TraceSpan]:
        """Get all spans for a trace."""
        return self._traces.get(trace_id, [])

    def get_active_trace_ids(self) -> list[str]:
        """Get IDs of traces with active spans."""
        return list(set(span.trace_id for span in self._active_spans.values()))

    def inject_context(self, span: TraceSpan) -> dict[str, str]:
        """Inject trace context into headers for propagation."""
        return {
            "X-Trace-ID": span.trace_id,
            "X-Span-ID": span.span_id,
            "X-Parent-Span-ID": span.parent_span_id or "",
        }

    def extract_context(self, headers: dict[str, str]) -> tuple[str, str | None]:
        """Extract trace context from headers."""
        trace_id = headers.get("X-Trace-ID", "")
        parent_span_id = headers.get("X-Parent-Span-ID") or None
        return trace_id, parent_span_id

    def clear(self) -> None:
        """Clear all traces."""
        with self._lock:
            self._traces.clear()
            self._active_spans.clear()
