apiVersion: builtin
kind: PatchTransformer
metadata:
  name: disaster-recovery-patch
patch: |-
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: brand-monitoring-restore
spec:
  backupName: brand-monitoring-backup
  includedNamespaces:
    - brand-monitoring-prod
  restorePVs: true

target:
  kind: Deployment
  name: brand-monitoring
