apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replacement-config
replacements:
  - source:
      kind: ConfigMap
      name: brand-monitoring-config
      fieldPath: data.LOG_LEVEL
    targets:
      - select:
          kind: Deployment
          name: brand-monitoring
        fieldPaths:
          - spec.template.spec.containers.[name=brand-monitoring].env.[name=LOG_LEVEL].value
        options:
          create: true
