apiVersion: builtin
kind: PatchTransformer
metadata:
  name: serviceaccount-patch
patch: |-
apiVersion: v1
kind: ServiceAccount
metadata:
  name: brand-monitoring-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/brand-monitoring-role

target:
  kind: Deployment
  name: brand-monitoring
