apiVersion: builtin
kind: PatchTransformer
metadata:
  name: backup-patch
patch: |-
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: partner-management-backup
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - partner-management-prod
    includedResources:
      - deployments
      - services
      - configmaps
      - secrets
    storageLocation: default
    ttl: 720h

target:
  kind: Deployment
  name: partner-management
