apiVersion: builtin
kind: PatchTransformer
metadata:
  name: headscale-control-patch
patch: |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-management
spec:
  template:
    metadata:
      annotations:
        headscale.io/control: "true"

target:
  kind: Deployment
  name: partner-management
